### ISSUE TITLE
Provide the tsdoc/typedoc/jsdoc proper commentaries to generated interfaces based on schema title and/or schema description.

### ISSUE THREAD

**Issue by majo44** [bcherny/json-schema-to-typescript#10]
Currently the commentaries are based only on description.

Eg.
For schema:

```json
{
  "title": "My Object",
  "description": "Some custom object",
  "type": "object",
  "properties": {
       "bar" : {
          "title": "Some property",
          "description": "Some property description",
          "type": "string"
       }
   }
}
```

We have: 

```javascript
/*
    Some custom object
  */
export interface MyObject {
  bar?: string; // Some property description
  [k: string]: any;
}
```

It will be nice to have:

```javascript
/**
 * Some custom object.
 */
export interface MyObject {
 /**
   * Some property.
   * Some property description.
   */
  bar?: string;
  [k: string]: any;
}
```

**Comment by bcherny** [comment]
Good idea - how about a heuristic:

- If a property only has a description, use an inline comment
- If a property has both a description and a title, use a block comment

Feel free to submit a PR, otherwise I'll get to this eventually.

**Comment by bcherny** [comment]
If `description` is set, it will produce a multi-line comment (newlines are supported).
If `title` is set, it will generate a type alias (see https://github.com/bcherny/json-schema-to-typescript/blob/master/test/cases/named-property.ts).
