### ISSUE TITLE
npm run build:server cannot be run twice

### ISSUE THREAD

**Issue by andreineculau** [bcherny/json-schema-to-typescript#108]
you're not excluding your dist folder in tsconfig.json

**Comment by bcherny** [comment]
Hi @andreineculau. You need to run `npm run clean` before rebuilding. I recommend running `npm run build`, which will do that for you.

**Comment by andreineculau** [comment]
`npm run clean` deletes the dist folder...
So you build, clean, build, clean, build, clean...
I wonder why I didn't think of that.
