### ISSUE TITLE
recursive loop -> json-schema-to-typescript crash

### ISSUE THREAD

**Issue by andreineculau** [bcherny/json-schema-to-typescript#110]
```json
{
    "type": "object",
    "additionalProperties": {
        "$ref": "#/definitions/foo"
    },
    "definitions": {
      "foo": {
        "oneOf": [{
          "type": "string"
        }, {
          "$ref": "#/definitions/foo"
        }]
      }
    }
}
```

**Comment by bcherny** [comment]
Tracked in https://github.com/bcherny/json-schema-to-typescript/issues/76, and dependsd on https://github.com/BigstickCarpet/json-schema-ref-parser/issues/37.

**Comment by andreineculau** [comment]
*GENERAL FEEDBACK* don't take this the wrong way, but I would suggest you reconsider your coding style to break down function calls. It was a pain getting to the bottom of this.

in https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L81
```js
  return generate(
    optimize(parse(await dereference(normalize(schema, name), _options.cwd))),
    _options
  )
```

is a much harder (to debug primarily, but also to read and comprehend) version of

```js
let normalizedSchema = normalize(schema, name);
let dereferencedSchema = await dereference(normalizedSchema, _options.cwd);
let ast = parse(dereferencedSchema);
let optimizedAst = optimize(ast);
let declaration = generate(optimizedAst);
return declaration;
```

same can be said about

* https://github.com/bcherny/json-schema-to-typescript/blob/master/src/generator.ts#L71
* https://github.com/bcherny/json-schema-to-typescript/blob/master/src/generator.ts#L104
* https://github.com/bcherny/json-schema-to-typescript/blob/master/src/generator.ts#L163
* ...

**Comment by bcherny** [comment]
@andreineculau Consider using a debugger like https://nodejs.org/api/debugger.html, https://github.com/node-inspector/node-inspector, or https://github.com/s-a/iron-node.

I prefer a functional style without intermediate variables - it makes it more clear what is used, by what, and in what sequence.

Of course it is a matter of taste, and you are more than welcome to fork this lib and rewrite it in your own preferred style. 

On a side note, have you seen the second bullet on the [CONTRIBUTING.md](https://github.com/bcherny/json-schema-to-typescript/blob/master/CONTRIBUTING.md#tips)? I have found it to be the most effective way to debug bad output.

**Comment by andreineculau** [comment]
@bcherny if you think this is a matter of taste and style, we're unfortunately talking past each other as no tool will improve what I pointed out. A breakpoint can only be set on **one** line, in a UI or with a `debugger` statement. Anyways, suit yourself.
