### ISSUE TITLE
Make internal functions public

### ISSUE THREAD

**Issue by christophercliff** [bcherny/json-schema-to-typescript#113]
Thanks for putting this library together. For my use case, I used your parser and AST and wrote my own formatter. For cases like these it would be useful if these internal functions were made public so they follow semver and have basic documentation and typings.

It might also cut down on API thrashing related to formatting options because users can use whatever formatting they prefer.

**Comment by bcherny** [comment]
Hi @christophercliff - Can you be more specific? Which functions in particular would be useful to expose?

Out of curiosity what was the different between your formatter's output and the default output?

**Comment by christophercliff** [comment]
My usage looks like:

```js
import { normalize } from 'json-schema-to-typescript/dist/src/normalizer'
import { parse } from 'json-schema-to-typescript/dist/src/parser'

myFormatter(parse(normalize(myJsonSchema)))
```

`myFormatter()` outputs a single type with everything inline (no declarations, exports, or interface reuse). This made it easier to inline the type definitions in my existing code generator. I also removed the styling and just run the output through [prettier](https://github.com/prettier/prettier).

**Comment by bcherny** [comment]
I didn't realize Prettier supports TypeScript - Seems like a great candidate for https://github.com/bcherny/json-schema-to-typescript/issues/45.

**Comment by bcherny** [comment]
That said, these internal functions can already be consumed (like you did in your example). Exporting them from the index would make it look like they should be consumed directly, when they are not meant to be, at least for most use cases.

I'll close this issue for now. If there's more interest in the future (meaning the use case is not a niche one), we can revisit this.
