### ISSUE TITLE
Single-property $ref converting to array

### ISSUE THREAD

**Issue by malbertSC** [bcherny/json-schema-to-typescript#115]
example:

object that references a single property
```
{
	"id": "main_thing",
	"$schema": "http://json-schema.org/schema#",
	"title": "main_thing",
	"type": "object",
	"properties": {
		"id": {
			"$ref": "references/id.json"
		}
	}
}
```
single property reference
```
{
	"id": "references/id.json",
	"$schema": "http://json-schema.org/schema#",
	"title": "ID",
	"type": "string",
	"minLength": 8,
	"maxLength": 8
}

```
I end up with this interface after conversion
```
export interface main_thing {
  id: Id;
}
export interface Id {
  [k: string]: any;
}
```
but I feel like I should be getting
```
export interface main_thing {
  id: string;
}
```
Is there any way I can specify that this property is NOT an array?  The id $ref is reused all over the place for the minLength and maxLength attributes and I'd rather not copy this into all the id fields
```
"type": "string",
"minLength": 8,
"maxLength": 8
```

**Comment by bcherny** [comment]
Thanks for the bug report @malbertSC! This is fixed in `json-schema-to-typescript@4.6.4`.
