### ISSUE TITLE
Unable to generate .d.ts file from apparently correct JSON file

### ISSUE THREAD

**Issue by respinha-ribeiro** [bcherny/json-schema-to-typescript#121]
Hello.

I have generated a JSON from a protobuf file using [protobuf-schema](https://github.com/devongovett/protobuf-jsonschema). When I introduce the file content in http://json2ts.com/, I get a correct .d.ts file. However, using json-schema-to-typescript directly, I am unable to obtain so.

My JSON file:
```
{
  "definitions": {
    "test.TestRequest": {
      "title": "TestRequest",
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      }
    },
    "test.TestResponse": {
      "title": "TestResponse",
      "type": "object",
      "properties": {
        "result": {
          "type": "string"
        }
      }
    }
  }
}
```

Output in http://json2ts.com/:
```
declare module namespace {

    export interface Value {
        type: string;
    }

    export interface Properties {
        value: Value;
    }

    export interface TestTestRequest {
        title: string;
        type: string;
        properties: Properties;
    }

    export interface Result {
        type: string;
    }

    export interface Properties2 {
        result: Result;
    }

    export interface TestTestResponse {
        title: string;
        type: string;
        properties: Properties2;
    }

    export interface Definitions {
        test.TestRequest: TestTestRequest;
        test.TestResponse: TestTestResponse;
    }

    export interface RootObject {
        definitions: Definitions;
    }
}
```
Output using json-schema-to-typescript (`json2ts <JSON src> <TS dst>`):
```
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export interface Test {
  [k: string]: any;
}
```

Any thoughts why?

**Comment by bcherny** [comment]
Hi @respinha-ribeiro! I haven't look at protobuf-schema or JSON2TS, but it appears to interpret your schema more optimistically than JSON-Schema-to-TypeScript does.

What the "definitions" property means is "here are a few things that might be used in my schema". Along with $ref, it's a way to factor out common definitions.

What you're looking for is "properties", which means "here are a few things that a schema must have to be considered valid".

To fix your schema, you should change "definitions" to "properties". I'm not sure how to get protobuf-schema to do that for you; consider opening an issue there and linking to this issue .
