### ISSUE TITLE
CWD option doesn't work on recursive refs

### ISSUE THREAD

**Issue by KurtPreston** [bcherny/json-schema-to-typescript#122]
When the `cwd` option is provided, it seems that it only sets the working path for the first file it encounters... if any of those refs themselves contain refs, those are currently being resolved as relative to their directory, rather than relative to the cwd.

So, that's a really confusing explanation, so here's an example.  Say I have three files:

**/project/a/a.json**

```javascript
{
  "$ref": "b/b.json"
}
```

**/project/b/b.json**

```javascript
{
  "$ref": "c/c.json"
}
```

**/project/c/c.json**

```
{
  "type": "number"
}
```

If I try to compile `b.json`, it will work just fine:

```javascript 
jsonSchemaToTypescript.compileFromFile("/project/b/b.json", {
  cwd: "/project"
})
```

If I try to compile `a.json`, it throw **Error: Error opening file "/project/b/c/c.json"**
```javascript
jsonSchemaToTypescript.compileFromFile("/project/a/a.json", {
  cwd: "/project"
})
```

Is there any way to tell `json-schema-to-typescript` to resolve **all** paths relative to the `cwd`, even nested refs?

**Comment by bcherny** [comment]
Pinging @BigstickCarpet - is this possible to do with json-schema-ref-parser?

See our usage here: https://github.com/bcherny/json-schema-to-typescript/blob/dd00eddf0162fe0058c71b4ad96ff76f4c4ab831/src/resolver.ts#L9.

**Comment by BigstickCarpet** [comment]
Per [the JSON References Spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03#section-4),  `$ref`s are relative to the current document, _not_ the root directory.

**Comment by bcherny** [comment]
Thanks for chiming in @BigstickCarpet. The spec is pretty clear about it, sorry @KurtPreston.

**Comment by KurtPreston** [comment]
Makes sense, fair 'nuff.  Thanks for the prompt reply, all!

As an aside though, it does seem like the `cwd` option in general violates the spec, no?  The working directory should *always* be the JSON file's directory, and you shouldn't be able to compile `b.json` in the example above.

**Comment by bcherny** [comment]
@KurtPreston `cwd` is exposed in case you're doing something weird. eg. if you npm installed jstt, `cwd` won't point to the right directory.

**Comment by KurtPreston** [comment]
@bcherny Cool, thanks for the clarification. Got it all working with relative paths instead.
