### ISSUE TITLE
Inspect Pattern Properties just for recursive definitions.

### ISSUE THREAD

**Issue by robertmassaioli** [bcherny/json-schema-to-typescript#124]
I just want to make it initially clear: I'm not looking for you to generate code for patternProperties. 

However, pattern properties do reference definitions that would be good to generate samples for. For example, in swagger we have the following definition:

      "paths": {
        "type": "object",
        "description": "Relative paths to the individual endpoints. They must be relative to the 'basePath'.",
        "patternProperties": {
          "^x-": {
            "$ref": "#/definitions/vendorExtension"
          },
          "^/": {
            "$ref": "#/definitions/pathItem"
          }
        },

Since this definition relies exclusively on patternProperties the generated object looks like this:

    /**
     * Relative paths to the individual endpoints. They must be relative to the 'basePath'.
     */
    export interface Paths {
    
    }

I think that we can all agree that this is not very useful. Frankly, a more useful implementation would be:

    /**
     * Relative paths to the individual endpoints. They must be relative to the 'basePath'.
     */
    export interface Paths {
        [name: string]: VendorExtension | PathItem;    
    }

But, like I said, I don't really want to solve that problem here. **The real problem is that VendorExtension and PathItem are never generated at all.**

This means that I can't even do some minor edits, after the fact, to the generated code, to make it behave as I expect. It would be really could if you could scan the patternProperties just to continue the code generation so the resultant file was easier to modify to be correct. 

Would that be an acceptable compromise? That way, you don't need to solve the patternProperties problem but users of your excellent tool could get 95% of the way to fully generated code instead of 60% of the way there in examples that make heavier use of patternProperties.

**Comment by bcherny** [comment]
Hi @robertmassaioli!

```ts
/**
 * Relative paths to the individual endpoints. They must be relative to the 'basePath'.
 */
export interface Paths {
    [name: string]: VendorExtension | PathItem;    
}
```

For the record, the problem with this interface is it permits assigning a `VendorExtension` to a key that matches `^/`, and a `PathItem` to a key that matches `^x-` (both of which are invalid according to the JSON-Schema). It would also allow assigning either a `VendorExtension` or a `PathItem` to a key that matches neither `^/` nor `^x-` (eg. the key `foo`), which is also invalid.

That said, generating interfaces for `VendorExtension` and `PathItem` does seem like a good idea. The downside is it's unclear where/how they are used, and the upside is - as you said - we should generate as much as possible while remaining correct.

For Phase 1, let's generate interfaces for `patternProperties`.

For Phase 2, to address the downside I mentioned, we can add to the comment (or create a comment) above the interface that uses `patternProperties`, indicating the additional unlinked interfaces it consumes. For your example, we would generate something like:

```ts
/**
 * Relative paths to the individual endpoints. They must be relative to the 'basePath'.
 *
 * Note: This interface also supports the following key patterns:
 *  - `^x-` VendorExtension
 *  - `^/` PathItem
 */
export interface Paths {}

export interface VendorExtension {...}

export interface PathItem {...}
```

PRs are welcome for Phase 1 if you want to take a stab at it! See [CONTRIBUTING.md](https://github.com/bcherny/json-schema-to-typescript/blob/master/CONTRIBUTING.md).

**Comment by bcherny** [comment]
@robertmassaioli @dekryptic Try out json-schema-to-typescript@5.1.0 and let me know what you think!

**Comment by robertmassaioli** [comment]
I will! Exciting! 😄
