### ISSUE TITLE
Format options not being used

### ISSUE THREAD

**Issue by jefbarn** [bcherny/json-schema-to-typescript#127]
Awesome idea to use Prettier, 
there's a bug where the style options aren't being used through...

https://github.com/bcherny/json-schema-to-typescript/blob/bad2bfc678ce4a9db3a56ffecb32b82833d1b050/src/index.ts#L83-L86

options aren't being passed to the format function

**Comment by bcherny** [comment]
That's what happens when you don't add tests huh... Thanks for noticing this so quickly @jefbarn.

Published 5.0.1.
