### ISSUE TITLE
FR: Support for types of native JavaScript objects such as Date, Regex, etc

### ISSUE THREAD

**Issue by adamduren** [bcherny/json-schema-to-typescript#128]
Is there a way to specify a value that is an object other than the standard JSON schema types such as a Date? The `ajv` JSON Schema Validator added keywords such as `instanceof` in order to support this so you might have a schema such as
```json
{ 
  "title": "IExample",
  "type": "object",
  "properties": {
    "createdDt": {
      "instanceof": "Date"
     }
  }
}
```

that would output to:

```
interface IExample {
  createdDt: Date;
}
```

If there is not a way do you have a general idea for the difficulty of implementing such feature and if it would be a welcome addition to the library or be considered out of scope. 

Here is a link to the library mentioned for reference.
https://github.com/epoberezkin/ajv-keywords#instanceof

Thank you, great library by the way!

**Comment by bcherny** [comment]
@adamduren This would fall under https://github.com/bcherny/json-schema-to-typescript/issues/2. I haven't thought much about what an extensions API would look like, since there are a few steps involved: parsing, optimization, code emission.

**Comment by bcherny** [comment]
If you want to look through the code and take a shot at specing out an API, go for it.
