### ISSUE TITLE
Generating patternProperties Objects

### ISSUE THREAD

**Issue by dekryptic** [bcherny/json-schema-to-typescript#129]
Is this schema:
```
{
  "id": "Parent",
  "type": "object",
  "patternProperties": {
    "^[a-zA-Z]+": {
      "id": "Child",
      "type": "object",
      "properties": {
        "aProperty": { "type":"string" }
      }
    }
  }
}
```
not supposed to generate a Child interface? I tested it out on https://bcherny.github.io/json-schema-to-typescript-browser/ and it only returned a Parent interface, i.e.
```
export interface Parent {
  [k: string]: any;
}
```

If not, is there any way to force json-schema-to-typescript to generate an interface for ALL objects, regardless of whether or not a specific portion of the JSON Schema specification can be supported in Typescript?

**Comment by bcherny** [comment]
Hi @dekryptic! What exactly would you expect the output to be in this case?

**Comment by dekryptic** [comment]
Would something like this:
```
export interface Parent {
  [k: string]: Child;
}
export interface Child {
  aProperty?: string;
  [k: string]: any;
}
```
be reasonable?

**Comment by bcherny** [comment]
I see. I believe this is a duplicate of https://github.com/bcherny/json-schema-to-typescript/issues/124. Feel free to reopen if you feel otherwise.
