### ISSUE TITLE
Sub-schemas generation

### ISSUE THREAD

**Issue by sebastien-de-saint-florent** [bcherny/json-schema-to-typescript#133]
Hi, 

I'm working on a project where JSON Schemas can have sub-schemas in "definitions" property. Some of those schemas are not directly referenced by the root schema but I still need to obtain their Typescript interface.

```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "aProperty": { "type": "string" }
    },
    "definitions": {
        "A": {
            "type": "object",
            "properties": {
                "anOtherProperty": { "type": "string" }
            }
        }
    }
}
```
In the example above, I would like "A" to be included in the result.

Do you think it's possible? I can contribute to the repo if you can show me the right place to add this feature.

Regards,

**Comment by bcherny** [comment]
Hi @sebastien-de-saint-florent! See https://github.com/bcherny/json-schema-to-typescript/issues/121#issuecomment-335321458 - does that sound reasonable to you? If I were you, I would pull out the definition into its own JSON-Schema. Otherwise, it's not clear if the definition is used or not, and how it's used.

**Comment by sebastien-de-saint-florent** [comment]
Hi @bcherny,
Thanks for your response. I don't think it's a good solution for me. The use case I'm trying address is really when the schema is used as a storage for multiple schemas (like it's done for an Open Api document for instance).
The workaround I've found is to generate each subschemas separately. But it doesn't work well with schemas that are referenced locally. It creates duplicates.

**Comment by bcherny** [comment]
Hey @sebastien-de-saint-florent - give v5.2.0 a try. Note that you will need to enable the `unreachableDefinitions` option. Let me know if this fixes your issue!

**Comment by sebastien-de-saint-florent** [comment]
Thank you @bcherny, it is working perfectly.
