### ISSUE TITLE
Support for One large file?

### ISSUE THREAD

**Issue by xavdid** [bcherny/json-schema-to-typescript#137]
Hey there! We've got a big exported schema that is structured roughly like this (but with many more schemas):

```json
{
  "version": "4.3.1",
  "schemas": {
    "AppSchema": {
      "id": "/AppSchema",
      "type": "object",
      "properties": {
        "version": {
          "description": "A version identifier for your code.",
          "$ref": "/VersionSchema"
        }
      }
    },
    "VersionSchema": {
      "id": "/VersionSchema",
      "description":
        "Represents a simplified semver string, from `0.0.0` to `999.999.999`.",
      "type": "string",
      "pattern": "^[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}$"
    }
  }
}
```

The full version is available [here](https://github.com/zapier/zapier-platform-schema/blob/master/exported-schema.json)

I realize this might be a slightly unorthodox arrangement, but I believe it's valid. I'm getting an error about the `$refs`:

```
% json2ts exported-schema.json foo.d.ts
Error opening file "/VersionSchema" 
ENOENT: no such file or directory, open '/VersionSchema'
```
Is there some configuration I can add to fix this, or do you know the way offhand I can split out the schemas so it'll work? 

Thanks a bunch!

**Comment by bcherny** [comment]
Hi @xavdid! This is unfortunately not a valid JSON-Schema, which is why you get an error (there is an [open issue](https://github.com/bcherny/json-schema-to-typescript/issues/48)) to add schema validation.

If you rename `"schemas"` to `"definitions"` and remove `"version"` and compile with the `unreachableDefinitions` flag set to `true`, this should compile fine.

Let me know if that's unclear!

**Comment by xavdid** [comment]
Appreciate the response @bcherny but I wasn't able to get it working - I'm still seeing the same error. I'm running a tiny script (with `node genDefs.js`) and the updated file you described (only a top-level `"definitions"` key): 

```js
const fs = require('fs');
const converter = require('json-schema-to-typescript');

// compile from file
converter
  .compileFromFile('./test.json', { unreachableDefinitions: true })
  .then(ts => fs.writeFileSync('foo.d.ts', ts));
```

Is the issue related to the `$ref` having a leading slash? When I remove it, the error is slightly different:

```
Error opening file "/Users/david/.../VersionSchema"
```

instead of 
```
Error opening file "/VersionSchema"
```

I can arrange the schemas in whatever file format we need (is there a standard or recommended arrangement I'm not seeing?), it just seemed like the one big file of everything would work.

**Comment by bcherny** [comment]
@xavdid Sorry, I didn't notice your $ref syntax. You want to use this pattern:

Before: `"$ref": "/VersionSchema"
After: `"$ref": "#/definitions/VersionSchema"`

When in doubt, take a look at the [tests](https://github.com/bcherny/json-schema-to-typescript/blob/master/test/e2e/ref.2.ts). :)

Does that fix your issue?

**Comment by xavdid** [comment]
@bcherny that did, awesome! 

There's a weird thing with identical interfaces being declared (`Thing`, `Thing1`, `Thing2`, etc) but I'll dig through other issues and see if it's a big deal before bothering you with it. 

Thanks a ton!

**Comment by giniedp** [comment]
@bcherny did you find a solution to overcome the Thing, Thing1, Thing2 ?
