### ISSUE TITLE
dependent project - readme update

### ISSUE THREAD

**Issue by ducin** [bcherny/json-schema-to-typescript#139]
Hi @bcherny, thanks for your great work!

I started a new project that uses `json-schema-to-typescript` along with RAML (RESTful API Modelling Language). It's called [`raml-to-typescript`](https://github.com/ducin/raml-to-typescript). It extracts all RAML types (let it be JSON Schema itself or RAML-defined types that have the same semantics/structure as JSON Schema) and uses your lib to generate TypeScript definitions using it. So it's just an integration tool. Works nice, I think.

Would you be opened to link to my project, if I create a PR (readme.md update)?

**Comment by bcherny** [comment]
Sure thing!

**Comment by ducin** [comment]
Wow, that was fast, thanks!

16.01.2018 18:21 "Boris Cherny" <notifications@github.com> napisał(a):
