### ISSUE TITLE
why useInterfaceDeclaration: false

### ISSUE THREAD

**Issue by kanreisa** [bcherny/json-schema-to-typescript#14]
https://github.com/bcherny/json-schema-to-typescript/blob/master/src/TsTypes.ts#L22

why?

**Comment by kanreisa** [comment]
and, why use type as interface?

https://github.com/bcherny/json-schema-to-typescript/blob/master/src/TsTypes.ts#L5
https://github.com/bcherny/json-schema-to-typescript/blob/master/src/TsTypes.ts#L61

**Comment by bcherny** [comment]
Cc @Speedy37

**Comment by Speedy37** [comment]
`type` allow to declare some "simple" types that can't be declared with `interface`.
for example: `type MyType = MyOtherType[]`
the default value for `useInterfaceDeclaration` is `false` because I prefer having all types with the same syntax and because I don't use the generated types with `extend` or `implements`.
`useInterfaceDeclaration` will only apply to declarations that can be expressed with the interface syntax.

**Comment by kanreisa** [comment]
cool implementation :anguished:

**Comment by bcherny** [comment]
@kanreisa If you disagree with the approach, please help us understand why?

**Comment by bcherny** [comment]
I have no strong opinions here. @kanreisa if you prefer interfaces to types, feel free to submit a PR and I'll be sure to take a look.

**Comment by bcherny** [comment]
In the meantime, closing this issue because it's not really an issue.

**Comment by kanreisa** [comment]
thanks tell me why

**Comment by bcherny** [comment]
@kanreisa Issues are for concrete bugs or enhancements. What you brought up is a stylistic issue, and is a matter of taste. Again, feel free to put up a PR if your style really does improve on the existing style in some way.

**Comment by kanreisa** [comment]
In this time, I decided to don't commit. Now I'm understand your policy. please don't care.

**Comment by bcherny** [comment]
@kanreisa I was cleaning up the code a bit, and realized that using types is indeed more awkward than interfaces. Additionally, the TS spec specifically recommends interfaces over types when possible:

> Interface types have many similarities to type aliases for object type literals, but since interface types offer more capabilities they are generally preferred to type aliases.

https://github.com/Microsoft/TypeScript/blob/af9dc417478672e05925b2af8b5b5924471bb0f9/doc/spec.md#310-type-aliases

I've updated the code in 728290415101f8da5b1b3226b56420bb5c9e3ede, and released it as 1.2.0. Thanks for the suggestion!
