### ISSUE TITLE
docs: 'bannerComment' option missing

### ISSUE THREAD

**Issue by ducin** [bcherny/json-schema-to-typescript#140]
According to the [source](https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L17-L24), there are 6 options you can pas to the option bag.

In the [readme.md docs](https://github.com/bcherny/json-schema-to-typescript#options) there are only 5, `bannerComment` is missing.

**Comment by bcherny** [comment]
Thanks for the suggestion @ducin - I added it to the docs.
