### ISSUE TITLE
Schema $ref to standalone type results in generation of type in generated typescript interface.

### ISSUE THREAD

**Issue by AndyDBell** [bcherny/json-schema-to-typescript#141]
I am not sure whether this is a configuration problem, expected behaviour or a bug but...

I declare a json schema file _id.schema.json_ containing:
```json
{
  "title": "TId",
  "type": "string"
}
```
Running _json-schema-to-typescript.compileFromFile( id.schema.json )_ generates:
```typescript
export type TId = string
```

I create a second json schema file _example.schema.json_ referencing _id.schema.json_ and containing:

```json
{
  "title": "IExample",
  "type": "object",
  "properties": {
    "id": {
      "$ref": "id.schema.json"
    },
    "name": {
      "type": "string"
    }
  },
  "required":[
    "id"
  ],
  "additionalProperties": false
}
```

Running _json-schema-to-typescript.compileFromFile( example.schema.json )_ generates:

```typescript
export type TId = string

export interface IExample {
  id: TId
  name?: string
}
```
Here the type **TId** is generated in addition to the  interface **IExample**.  i.e. **TId** is defined twice, once in each file.

This makes it impossible to use the generated code in a typescript program with out manual editing to remove the second definition of **TId**.

**Comment by bcherny** [comment]
Hi @AndyDBell! You can avoid declaring externally referenced types by setting the `declareExternallyReferenced` option to `false`. In the future, you'll be able to use [batch mode](https://github.com/bcherny/json-schema-to-typescript/issues/16) to generate a set of typings at once with automatic deduping.

Let me know if that works for your use case!

**Comment by AndyDBell** [comment]
Hi Boris,

Thanks for your response.  

I have tried setting _declareExternallyReferenced_ to false in the compileFromFile options but the output did not change!

This is my options object:

```javascript
  const options: any = {
    cwd: './src/models/jsonschema',
    declareExternallyReferenced: false,
    unreachableDefinitions: false,
    style: {
      semi: false,
      singleQuote: true,
    }
  }
```

The generated typescript is the same as with _declareExternallyReferenced_ set to true.

**Comment by bcherny** [comment]
Hmm could you upload a self-contained repro case? This does seem like a bug. In the meantime, generating multiple copies of a type should be fine - TypeScript will merge them for you as best it can.

**Comment by AndyDBell** [comment]
Zipped self contained repro code shared on onedrive at https://1drv.ms/u/s!ArpiIInQBexRhZY9b-gSPf3z1QxXTQ.
Note - included everything including node_modules, dist etc.  Editor is vscode.

**Comment by bcherny** [comment]
Thanks for the repro case @AndyDBell.

What's happening here is that `declareExternallyReferenced` isn't working as expected for primitive types (as opposed to interfaces).

I maintain this project in my spare time, and won't have time to fix this soon. Sorry about the inconvenience. Also, contributions are welcome!

In the meantime, you have 3 options for workarounds: (1) remove the type alias from your JSON-Schema, (2) manually edit the outputted file, or (3) combine your schemas into one.

**Comment by AndyDBell** [comment]
Hi Boris,

 

Understood.  I thought that the problem was as you described and tried to trace through your code to find a solution but it got a bit complex.

 

Thanks for creating this project in your spare time.  We are flat out on our own project but, if I find a spare moment, I will try to look further into this problem for you.

 

We intend to use our json schema to generate mongoose schema, swagger definitions etc so we have written a pre-processor to replace references to simple types with the type prior to passing to your code.

 

Once again, thanks for creating this useful package.

 

Andy

**Comment by adamduren** [comment]
@AndyDBell A workaround I'm currently using is to use the the `tsType` extension to name the type instead of `$ref`erencing it. You just have to make sure in whatever script you are using to generate the type definitions includes the type once. Hope this helps.

**Comment by Pomaio** [comment]
I fixed this problem in my repo with this code: 

read json: 
```
const sources = await Promise.all(
    schemas
      .filter(v => v.endsWith('json'))
      .map(async v => {
        const dereferenced = await refParser.dereference(
          _pathToJSON_
        );
        return  await compile(dereferenced, v.replace('.json', ''), _options_);
      })
  );
```

and filtred existing interfaces
```
// get first nesting level
const floatSources = sources.reduce((acc, s) => [...acc, ...s.split('export').filter(v => !!v && /(interface|enum|type)/g.test(v)).map(v => 'export' + v)], []);  

const getInterfaceName = (source) => source.match(/export (interface|enum|type) (\w+)/)[2];

let existingInterfaces = [];

const filtredSources = floatSources.filter((source) => {
  const interfaceName = getInterfaceName(source);
  if (existingInterfaces.includes(interfaceName)) {
    return false
  }
  existingInterfaces.push(interfaceName);
  return true;
});
```

**Comment by Roaders** [comment]
`declareExternallyReferenced` nearly fixed my use case except that there were no imports. In my example `ICompany` references `IEmployee`. In the generated code `Iemployee` was not added to the `d.ts` file for `ICompany` but there was no import for `IEmployee` so it fails.

**Comment by bcherny** [comment]
Merging into #258
