### ISSUE TITLE
Use of `allOf` makes some properties disappear

### ISSUE THREAD

**Issue by vsund** [bcherny/json-schema-to-typescript#152]
First of all, big thanks for this library!

I'm not sure whether I misunderstood what I do or this tool produces wrong output. But somehow it's not doing what I expected :D

I have the two schemas from below. `Person.json` should take all rules from `Person.json` and add a `name` property.
If I throw them into `json2ts` I get the following output
```ts
export type Person = {
	'@context': string;
	'@type': string;
	'@id': string;
	[k: string]: any;
};
```
While this is in theory correct (`[k: string]: any` includes everything `Person.json` specifies), it's hard to specify properties in `Person.json`. I expected it to include the `name` property explicitly:
```ts
export type Person = {
	'@context': string;
	'@type': string;
	'@id': string;
	name?: string; // <---
	[k: string]: any;
};
```

Also wondering why the output from `Person.json` is a type literal while the one from `Profile.json` is an interface 🤔 

Anyway, thanks for all help in advance.

---
#### `Profile.json`
```json
{
	"$schema": "http://json-schema.org/schema#",
	"type": "object",
	"properties": {
		"@context": { "type": "string" },
		"@type": { "type": "string" },
		"@id": { "type": "string" }
	},
	"required": ["@context", "@type", "@id"]
}
```

#### `Person.json`
```json
{
	"$schema": "http://json-schema.org/schema#",
	"allOf": [{ "$ref": "src/profiles/schemas/Profile.json" }],
	"type": "object",
	"properties": {
		"name": { "type": "string" }
	},
	"required": [
		"name"
	]
}
```

#### `Profile.json.d.ts`
```ts
export interface Profile {
	'@context': string;
	'@type': string;
	'@id': string;
	[k: string]: any;
}
```

**Comment by bcherny** [comment]
Hi @vsund! This is probably a symptom of https://github.com/bcherny/json-schema-to-typescript/issues/96. What happens when you update your schema like this:

```json
{
  "$schema": "http://json-schema.org/schema#",
  "allOf": [
    {
      "$ref": "src/profiles/schemas/Profile.json"
    },
    {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    }
  ]
}
```

**Comment by vsund** [comment]
Wow, that was quick ;) Saw that issue, but somehow I wasn't able to connect it to my problem.

Your suggestion gives me a
```ts
export type Person = {
	'@context': string;
	'@type': string;
	'@id': string;
	[k: string]: any;
} & {
	name: string;
	[k: string]: any;
};
```

which works like a charm. Will go with this until #96 is resolved.

I guess now it makes sense why it's a type literal. I believe you cannot link two interfaces?

**Comment by bcherny** [comment]
It’s mostly a stylistic choice, because sometimes unnamed schemas are declared inline and sometimes we pull them out. If you want an interface, define an “id” property on Person’s schema.
