### ISSUE TITLE
Re-use generated interfaces for $ref in allOf

### ISSUE THREAD

**Issue by vsund** [bcherny/json-schema-to-typescript#154]
Hey,

I tried to externalize some complex properties from my main schema `Person.json` to use the (sub) interfaces separately in the code.
For example my `Person.json` schema has an `account` property and I put the schema from this into `components/Account.json`.

It would be cool to re-use the declared interfaces for these types. E.g.
```ts
export type Person = {
	name?: string;
	account?: Account[];
	[k: string]: any;
};
```

For all the used schemas etc see below. Please note that I simplified the schema, if something doesn't match please let me know.

---

<details>
<summary>Person.json</summary>

```json
{
"$schema": "http://json-schema.org/schema#",
	"type": "object",
	"properties": {
		"name": { "type": "string" },
		"account": {
			"type": "array",
			"items": {
				"allOf": [{ "$ref": "components/Account.json" }]
			}
		}
	}
}
```
</details>

<details>
<summary>components/Account.json</summary>

```json
{
	"$schema": "http://json-schema.org/schema#",
	"type": "object",
	"properties": {
		"@type": { "type": "string" },
		"role": { "type": "string" },
		"service": { "type": "string" },
		"identifier": { "type": "string" },
		"proofType": { "type": "string" },
		"proofUrl": { "type": "string" },
		"proofMessage": { "type": "string" },
		"proofSignature": { "type": "string" }
	}
}
```
</details>

<details>
<summary>Person.json.d.ts</summary>

```ts
export type Person = {
	name?: string;
	account?: {
		'@type'?: string;
		role?: string;
		service?: string;
		identifier?: string;
		proofType?: string;
		proofUrl?: string;
		proofMessage?: string;
		proofSignature?: string;
		[k: string]: any;
	}[];
	[k: string]: any;
};
```
</details>

<details>
<summary>components/Account.json.d.ts</summary>

```ts
export interface Account {
	'@type'?: string;
	role?: string;
	service?: string;
	identifier?: string;
	proofType?: string;
	proofUrl?: string;
	proofMessage?: string;
	proofSignature?: string;
	[k: string]: any;
}
```
</details>

**Comment by bcherny** [comment]
Hi @vsund! We use the presence of the `id` property as a heuristic for whether or not to pull out a subschema into its own `type` alias. Try adding `id` to Account.json's schema.

You might run into an issue where we generate the linked schema twice - let me know what the result is!

**Comment by vsund** [comment]
Thanks for the help! Indeed generated twice:

#### `Person.json`
```ts
export type Person = {
	name?: string;
	account?: AccountJson[];
	[k: string]: any;
};

export interface AccountJson {
	'@type'?: string;
	role?: string;
	service?: string;
	identifier?: string;
	proofType?: string;
	proofUrl?: string;
	proofMessage?: string;
	proofSignature?: string;
	[k: string]: any;
}
```

The same `AccountJson` interface is is also in `components/Account.json`. Anything I could/should do about this?

**Comment by bcherny** [comment]
This is a known issue https://github.com/bcherny/json-schema-to-typescript/issues/16. You could avoid compiling Account.json for now, or you could send a PR for the issue :)

In either case this shouldn't affect anything -- TS will merge the two `AccountJson` declarations for you automatically, so while the output is ugly, it works well.

**Comment by vsund** [comment]
Yeah, it's basically only the ugly output. But since I don't commit these files I think it's ok :)

Thanks for all the help! ;)
