### ISSUE TITLE
allOf with additional required fields doesn't make them required

### ISSUE THREAD

**Issue by thejuan** [bcherny/json-schema-to-typescript#157]
You should be able to specify a reference to a type and a set of required fields using allOf.
At the moment the specified required fields are not required in the typescript (i.e. generated wtih a ? on the property)

```js
{
  type: 'object',
  required: [ 'name', 'location' ],
  additionalProperties: false,
  properties: {
    location: {
      allOf: [
        { $ref: 'location' },
        { required: [ 'postalCode' ] }
      ]
    },
    name: { type: 'string' },
    website: { type: 'string' }
  }
}
```

In above postalCode should be marked as required, but it's not ATM
https://stackoverflow.com/questions/41958392/extending-ref-with-additional-required-fields

**Comment by bcherny** [comment]
@handrews @schani Do you know if this is kosher - `{ required: [ 'postalCode' ] }` should make `postalCode` required in `{ $ref: 'location' }`?

**Comment by schani** [comment]
Yes, that is correct.  This is also a bug in quicktype that I just discovered ;-)

**Comment by bcherny** [comment]
Related: https://github.com/bcherny/json-schema-to-typescript/issues/96

**Comment by thejuan** [comment]
I work around this by pre-processing the schemas with
https://github.com/bojand/json-schema-deref
and
https://github.com/mokkabonna/json-schema-merge-allof?files=1
