### ISSUE TITLE
Renamed types on consecutive UPPERCASE chars

### ISSUE THREAD

**Issue by henkesn** [bcherny/json-schema-to-typescript#159]
Hi guys, first of all, thank you for your great work!
I just noticed an unexpected behaviour with the converter.

When having type names with several uppercase chars in a row, in the result get lowercased. Only the first character remains capital.

Example:

```
{
    "id":"#",
    "definitions": {
        "exampleDTO": {
            "type": "object",
            "title": "exampleDTO",
            "properties": {
                "foo": {
                    "type": "string"
                }
            }
        }
    }
}
```
leads to
```
export interface ExampleDto {
  foo?: string;
  [k: string]: any;
}
```
the originally named ExampleDTO is generated as interface ExampleDto.

I think that should be fixed as this could also lead to naming conflicts.

**Comment by bcherny** [comment]
Hi @henkesn! There's actually a TODO in the code for just that! If you'd like to PR this feature:

1. Update this function: https://github.com/bcherny/json-schema-to-typescript/blob/91679020eebba58198ba0f5d5c59e6c3e953c4be/src/utils.ts#L55
2. Be sure to add some E2E tests
