### ISSUE TITLE
Batch mode for generating interfaces for several JSON-schemas at once

### ISSUE THREAD

**Issue by bcherny** [bcherny/json-schema-to-typescript#16]
To avoid generating the same interface twice.

https://github.com/bcherny/json-schema-to-typescript/pull/15#discussion_r77439790

**Comment by erykpiast** [comment]
So how the API may look like? `json2ts -i *.json -o ???`. Should we allow to specify some kind of renaming pattern (like `sed` syntax) or just concatenate all interfaces to one `ts` file when output file is specified and create `[orig_name_wo_extension].d.ts` files in case it isn't?

**Comment by bcherny** [comment]
Glob syntax sounds good to me. 

I would separate the work into 2 parts:

- Part 1 (easy) - each input file maps to an output file (user can take care of concating), no optimization (TS takes care of type merging, so duplicates are fine)
- Part 2 (harder) - each input file maps to an output file, common types are pulled out into a common file to avoid duplication

**Comment by erykpiast** [comment]
I like the split :+1:.

So, for the first step, results would be like 
```
$ ls *.json
a.json b.json c.json
$ json2ts *.json
$ ls *.d.ts
a.d.ts b.d.ts c.d.ts
``` 
no matter if `a` `b` or `c` contain different or equal interfaces, right?

How do we want to prevent people from specifying output file for multiple inputs? Just throw an error?

**Comment by bcherny** [comment]
Exactly. Error or warning is probably fine. I agree error might be better to keep the API as strong as possible.

**Comment by tomekp** [comment]
I expect a little different behavior:
I want to be able to generate multiple `*.ts` files, one for each defined interface (from each schema). So if some type would be generated many times it would just overwrite the same file.

It seems I'd need to add a function to generator that returns a dictionary like `{"file name for type": "file content"}` (+ change all `declareXxx` functions to return an array of strings instead of returning concatenated string, and figure out imports).

The tricky part seems to be generating file names (for `SomeType` in schema I want to get `some-type.model.ts` file) so I'd expect user to provide file name generating function.

If that's OK for you I'd start working on a PR providing that.

**Comment by bcherny** [comment]
@tomekp I'm not convinced that approach is better. Ostensibly if someone has already taken the trouble to put, say, definitions A B and C in schema X and D E and F in schema Y, for their case this is a natural way to modularize and group their schemas. So when we generate TypeScript code from those schemas, it seems natural to put schemas A B and C in X.d.ts and D E and F in Y.d.ts.

If a user wanted to generate 1 file per schema, all they would need to do is feed in one file per schema (a trivial refactoring of their JSON-Schemas).

On the other hand, under your scheme a user couldn't do the opposite, and generate one file containing several schemas by feeding in one file with several schemas.

What do you think?

**Comment by bytesnz** [comment]
This is a kind of related idea. I was just looking at using this and z-schema for the schemas/typings in one of my projects. I think it is handy to support passing schemas as an array to `compile` so that $refs can be supported between the schemas given in the array. The functionality would be the same as passing the multiple files to `json2ts` I would think, apart from outputting a single string.

**Comment by eweap** [comment]
@bytesnz @bcherny  You can take a look to my fork (https://github.com/eweap/json-schema-to-typescript/tree/compile-dir)

I think i have partially achieved the part 1 of the solution.

I made these modifications urgently in order to be able to use the concatenated output in our projects. But I think it's a good start.

I have not made a pull request at the moment for lack of time and because I struggled with the Jest tests (which I had never used) but I think I will finish a day when I will have more time.

Below is an overview of how I use compileDir to build final `index.d.ts` output:

```javascript
import { outputFileSync } from 'fs-extra';
import { compileFromDir } from 'json-schema-to-typescript';

import { cleanDirectory, compilationOptions } from './utils';

const schemasDir = 'schemas';
const typesDir = 'typings';
const indexFile = 'index.d.ts';
const indexPath = `${typesDir}/${indexFile}`;
const exportFile = 'export.d.ts';
const exportPath = `${typesDir}/${exportFile}`;

export function buildTypes(): Promise<any> {
    // Clean the typings directory
    cleanDirectory(typesDir);

    // When compilation is finished
    return compileFromDir(schemasDir, compilationOptions).then(
        definitions => {
            // Build a global definition files
            const globalOutput = definitions.map(definition => definition.definition);
            outputFileSync(indexPath, globalOutput.join('\n'));

            // Generate an index file
            const exportFileOutput = definitions.map(definition => {
                // Remove root directory
                let exportPath = definition.filepath.replace(schemasDir, '.');

                // Remove extension for export
                exportPath = exportPath.replace('.json', '');

                return `export * from '${exportPath}';`;
            });
            outputFileSync(exportPath, exportFileOutput.join('\n'));

            // Generate the definitions files
            return definitions.map(definition => {
                let filepath = definition.filepath.replace(`${schemasDir}/`, '');
                // Remove extension
                filepath = filepath.replace('.json', '.d.ts');

                // Retrieve definition output
                const definitionOutput = definition.definition;

                const definitionPath = `${typesDir}/${filepath}`;

                outputFileSync(definitionPath, definitionOutput);
            });
        },
        // Failed
        error => console.error(error)
    );
}
```

Hope it helps (And thx @bcherny for the good work !)

**Comment by bytesnz** [comment]
How do you put multiple schemas in a single file?

Buffering out my previous comment, I am currently building schema and interfaces for a svg drawing project I am working on and wanted the documentation, type checking and typescript definitions to be done through json-schemas, using json-schema-to-typescript, z-schema. My idea was to have all the schemas in a folder/file hierarchy in a structure that could be ingested by json-schema-to-typescript and be able to get them in a format for z-schema. I am tackling the json-schema-to-typescript part first and have files like the those below, but can't find a way to get json-schema-to-typescript to output the interfaces.
`interaction.json`
```json
{
  "title": "Vector Space History Object definitions",
  "definitions": {
    "InteractionType": {
      "type": "string",
      "description": "The type of interaction",
      "enum": [
        "point",
        "multipoint",
        "key"
      ]
    },
    "AttachmentType": {
      "type": "string",
      "description": "If part of an interaction attachment series, the type of series the event is part of\n      ",
      "enum": [
        "click",
        "drag"
      ]
    },
    "Interaction": {
      "type": "object",
      "description":  "Interaction event used to pass an interaction with a Vector Space to tools and other listeners\,
      "properties": {
        "event": {
          "$ref": "Event"
        },
        "type": {
          "$ref": "#definitions/InteractionType"
        },
        "attachmentType": {
          "$ref": "#definitions/AttachmentType"
        },
        "coordinates": {
          "oneOf": [
            {
              "$ref": "schema/objects#definitions/Coordinate"
            },
            {
              "type": "array",
              "description": "Array of coordinates of the interaction",
              "items": {
                "$ref": "schema/objects#definitions/Coordinate"
              }
            }
          ]
        },
        "middleCoordinates": {
          "$ref": "schema/objects#definitions/Coordinate"
        }
      },
      "required": [
        "event",
        "type",
        "coordinates"
      ]
    }
  }
}
```

`schema/objects.json`
```json
{
  "definitions": {
    "VectorSpace": {
      "type": "array",
      "description": "A Vector Space containing layers and objects",
      "items": {
        "oneOf": [
          {
            "$ref": "#definitions/Point"
          },
          {
            "$ref": "#definitions/Line"
          },
          {
            "$ref": "#definitions/Layer"
          }
        ]
      }
    },
    "Object": {
      "type": "object",
      "properties": {
        "id": {
          "type": "number",
          "description": "Vector Space-wide unique identifier of the object"
        }
      }
    },
    "Coordinate": {
      "type": "array",
      "items": [
        {
          "type": "number",
          "description": "x coordinate"
        },
        {
          "type": "number",
          "description": "y coordinate"
        }
      ],
      "minItems": 2,
      "maxItems": 2
    },
    "Point": {
      "type": "object",
      "description": "Point on the Vector Space",
      "extends": "#definitions/Object",
      "properties": {
        "point": {
          "type": "array",
          "description": "Coordinates of the point on the Vector Space"
        }
      },
      "required": [
        "id",
        "point"
      ]
    },
    "Line": {
      "type": "object",
      "description": "Line on the Vector Space",
      "extends": "#definitions/Object",
      "properties": {
        "line": {
          "type": "array",
          "description": "Coordinates of the line",
          "items": {
            "$ref": "#definitions/Coordinate"
          }
        }
      },
      "required": [
        "id",
        "line"
      ]
    },
    "Layer": {
      "type": "object",
      "description": "Vector Space Layer",
      "extends": "#definitions/Object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the layer"
        }
      },
      "required": [
        "id",
        "name"
      ]
    }
  }
}
```

**Comment by Leeingnyo** [comment]
Hi, Please see following example.

`Album.schema.json`
```js
{
  "$schema": "http://json-schema.org/schema#",
  "id": "Album.schema.json",
  "title": "Album",
  "required": [
    "name"
  ],
  "allOf": [
    { "$ref": "Item.schema.json" },
    {
      "properties": {
        "description": {
          "type": "object",
          "$ref": "Description.schema.json"
        },
        "name": { "type": "string" },
        "releaseDate": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  ]
}
```

Above one converts to below now (I editted something manually).

`Album.d.ts`
```ts
export type Album = Item & {
  description?: Description;
  name?: string;
  releaseDate?: string;
  [k: string]: any;
};
export interface Item = {
  type?: string;
  [k: string]: any;
};
export interface Description = {
  content?: string;
  [k: string]: any;
};
```

I suggest this form.

`Album.d.ts`
```ts
import { Item } from 'Item.d.ts';
import { Description } from 'Description.d.ts';

export type Album = Item & {
  description?: Description;
  name?: string;
  releaseDate?: string;
  [k: string]: any;
};
```
 
Traversing AST one depth only, generate ECMAScript module import statements for type dependency.
We can reuse types.

**Comment by Lange** [comment]
I'd quite like this feature and would be willing to contribute to a cash bounty for it. If there are others also interested in contributing to a cash bounty, perhaps we can make this worth someone's time to implement.

**Comment by Ethan-Arrowood** [comment]
I just opened a PR that should resolve this issue.

**Comment by Ethan-Arrowood** [comment]
Because of stagnation I've published a npm module that enables this feature, api only for now. https://www.npmjs.com/package/compile-schemas-to-typescript
