### ISSUE TITLE
Trivial schema fails typescript compiler

### ISSUE THREAD

**Issue by cchalm** [bcherny/json-schema-to-typescript#162]
Compiling this program...

```js
import { compile } from 'json-schema-to-typescript';

const mySchema = {
  type: 'string'
};

compile(mySchema, 'MySchema');
```

...produces this error:

```
test.ts(7,9): error TS2345: Argument of type '{ type: string; }' is not assignable to parameter of type 'JSONSchema4'.
  Types of property 'type' are incompatible.
    Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" | "any" | "integer" | "array" | "null" | JSONSchema4Ty...'.
```

I was sure I was doing something wrong, but I came up empty after a couple hours of investigation, and now I'm not sure. This module produces typescript interfaces from jsonschemas, so I assumed the module itself would play nice with typescript. Is that not true?

**Comment by cchalm** [comment]
Since luck is cruel, I believe I figured this out a couple minutes after posting. The type of the value assigned to the property called "type" in the object literal mySchema is inferred to be "string". The string literal is "string", which satisfies the type `"string" | "number" ...`, but the inferred type "string" is too broad to be assigned to the more restrictive actual type. So I just need to get access to the interface JSONSchema4 and explicitly annotate the declaration of mySchema with that... I think. My apologies for cluttering up your issue board with my misunderstanding of typescript.

**Comment by DataTables** [comment]
I reckon I'm being thick, but I'm seeing basically the same issue and I don't really understand how it can be fixed. Given the schema:

```
{
	"title": "config",
	"type": "object",
	"properties": {
	 	"text": {
			"type": "object",
			"properties": {
				"format": {
					"type": "string",
					"enum": ["1", "2", "3", "4", "5"]
				}
			}
		}
	}
}
```

I get the error:

```
error TS2345: Argument of type '{ "title": string; "type": string; "properties": { "text": { "type": string; "properties": { "format": { "type": string; "enum": string[]; }; }; }; }; }' is not assignable to parameter of type 'JSONSchema4'.
  Types of property 'properties' are incompatible.
    Type '{ "text": { "type": string; "properties": { "format": { "type": string; "enum": string[]; }; }; }; }' is not assignable to type '{ [k: string]: JSONSchema4; }'.
      Property '"text"' is incompatible with index signature.
        Type '{ "type": string; "properties": { "format": { "type": string; "enum": string[]; }; }; }' is not assignable to type 'JSONSchema4'.
          Types of property 'properties' are incompatible.
            Type '{ "format": { "type": string; "enum": string[]; }; }' is not assignable to type '{ [k: string]: JSONSchema4; }'.
              Property '"format"' is incompatible with index signature.
                Type '{ "type": string; "enum": string[]; }' is not assignable to type 'JSONSchema4'.
                  Types of property 'type' are incompatible.
                    Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" | "any" | "integer" | "array" |"null" | JSONSchema4TypeName[]'.
```

The resulting typescript looks fine, but I don't understand how to address this compile time error.

Any suggestions?
