### ISSUE TITLE
declareExternallyReferenced does not work when referencing a definition that uses allOf

### ISSUE THREAD

**Issue by adamduren** [bcherny/json-schema-to-typescript#165]
See repo for easy reproduction:
https://github.com/adamduren/json-schema-to-typescript-output-bug

**From README.md:**

When using `allOf` the `declareExternallyReferenced` option appears to be ignored.

To recreate:

```
# Checkout repo
> npm i
> node ./generate-interfaces.js
```

`generate-interfaces.js` generates interfaces for both `correct.json` and `incorrect.json`.

Both files are the same except for the objects that they externally reference.

`correct.json` references `external-object.json` which is just a standard object definition with one property. In the generated output `IExternalOject` is not defined as expected.

`incorrect.json` references `external-all-of.json` is the same as `external-object.json` with the exception that the object definition is wrapped in an `allOf` In the generated output `IExternalAllOf` is unexpectedly defined.

**Comment by bcherny** [comment]
Published 6.0.2
