### ISSUE TITLE
Stick to one lockfile

### ISSUE THREAD

**Issue by qm3ster** [bcherny/json-schema-to-typescript#177]
`package-lock.json` is newer than `yarn.lock`.
Perhaps one of them should be deleted from the repo and added to `.gitignore`.
Also consider using `pnpm` (else, sticking its `shrinkwrap.yaml` into `.gitignore` as well.)

**Comment by bcherny** [comment]
https://github.com/bcherny/json-schema-to-typescript/commit/3fbdab611388c8fc68eded2d4970eff353096ec2
