### ISSUE TITLE
 Use 'Array<T>' instead 'T[]' for tslint

### ISSUE THREAD

**Issue by lebang** [bcherny/json-schema-to-typescript#192]
[tslint] Array type using 'T[]' is forbidden for non-simple types. Use 'Array<T>' instead. (array-type)
could u fix it? 
thank u.

**Comment by adamduren** [comment]
@lebang I ran into this as well. Instead of handling this rule as a one off it might be better to support passing an optional tslint instance into the options similar as to how prettier can be passed in. Currently I am post processing my files as part of my json-schema-to-typescript pipeline.

**Comment by bcherny** [comment]
@adamduren That’s a great idea! Does TSLint have a programmatic API to apply auto-fixes? Is there an existing auto-fix for array style?

**Comment by deadNightTiger** [comment]
Seeing as everybody will have different lint rules, maybe just emit `/* tslint:disable */` as the first line of the generated file? Not all rules will have auto fixes available (for example `object-literal-sort-keys`, which is enabled by the `tslint:recommended` preset).

**Comment by adamduren** [comment]
@deadNightTiger That's what I wound up doing. @bcherny I did some poking around and I didn't find a public or well-documented api. Because it's all JS/TS it could be engineered but probably not worth the effort.

**Comment by bcherny** [comment]
Sounds good. If someone wants to add the tslint ignore annotation, I’ll merge it!

**Comment by Hoishin** [comment]
You can exclude files when running tslint. IMO it shouldn't emit `/* tslint: disable */` as someone might want to lint the emit files.

**Comment by bcherny** [comment]
@hoishin Do you have a use case for punting emitted files?

**Comment by Hoishin** [comment]
@bcherny when you want to control the emitted files...? not concrete one, but I don't think it's write to control library specific feature, especially this case it's super easy to just exclude the emitted files while it's really hard to remove the `tslint:disable` line in emitted files.

**Comment by deadNightTiger** [comment]
@Hoishin it's not hard to remove it though, you could just use non-default bannerComment.

**Comment by Hoishin** [comment]
@deadNightTiger Ah missed that it is included in the banner. That makes sense.
