### ISSUE TITLE
How to inherits from two definitions?

### ISSUE THREAD

**Issue by odykyi** [bcherny/json-schema-to-typescript#198]
I have interface on TS, and it works, because I define this interface manually
```
// GetMysqlSuccessPayload.d.ts
import { MysqlPayload } from '../../MysqlPayload ';
import { MysqlCredential } from '../MysqlCredential ';

export interface GetMysqlSuccessPayload extends MysqlPayload, MysqlCredential {

}
```
I want not write manually interface in typescript, I want to use library `json-schema-to-typescript`, but I can't

How I can rewrite this TS code to json-schema, and how I can use json-schema-to-typescript `extends` from `two` interfaces? 
now library `json-schema-to-typescript` doesn't support inheritance from more than two interfaces?

and I try to use `extends` in `basicTypes.json`
```
{
  "definitions": {
    "GetMysqlSuccessPayload ": {
      "title": "GetMysqlSuccessPayload",
      "type": "object",
      "extends": {
        "$ref": "#/definitions/MysqlPayload ",  // How to inherits from two definitions
        "$ref": "#/definitions/MysqlCredential "
      }
    }
    .......
  }
}
```

**Comment by bcherny** [comment]
Hey there @odykyi! You want `$allOf`:

```json
{
  "definitions": {
    "GetMysqlSuccessPayload ": {
      "title": "GetMysqlSuccessPayload",
      "type": "object",
      "$allOf": [
        {"$ref": "#/definitions/MysqlPayload"},
        {"$ref": "#/definitions/MysqlCredential"}
      ]
    }
  }
}
```

See example output [here](https://github.com/bcherny/json-schema-to-typescript/blob/master/test/e2e/allOf.ts), or read more [here](https://github.com/json-schema-org/json-schema-spec/issues/348).
