### ISSUE TITLE
scripts prop on generated schema for package.json needs to be fixed

### ISSUE THREAD

**Issue by isabellachen** [bcherny/json-schema-to-typescript#210]
Using the online schema to typescript coverter with the [package.json schema](http://json.schemastore.org/package) I get a `scripts?` prop under CoreProperties with a list of optional props (I removed most of the props for brevity)

```js
scripts?: {
    prepublish?: string;
    prepare?: string;
    prepublishOnly?: string;
    [k: string
    ]: string;
}
```
My compiler is freaking out because `Property 'prepublish' of type 'string | undefined' is not assignable to string index type 'string'`. The same goes for the entire list of props. To get around this issue, I had to change the last two lines to:

```js
scripts?: {
    prepublish?: string;
    prepare?: string;
    prepublishOnly?: string;
    [k: string
    ]: string | undefined;
}
```
And it worked fine.

**Comment by bcherny** [comment]
Tracking in #235
