### ISSUE TITLE
schema without id or title does not generate any output or error

### ISSUE THREAD

**Issue by aucampia** [bcherny/json-schema-to-typescript#214]
Currently if a schema does not have `id` or `title` it is not compiled, this is not in itself an issue but the lack of some error seems sub optimal.

### Current Behaviour:

No `id` or `title`
```
$ echo '{ "properties": { "a": {} } }' | json2ts; echo $?
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */
0
```

With `id`

```
$ echo '{ "id": "foo", "properties": { "a": {} } }' | json2ts; echo $?
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Foo {
  a?: any;
  [k: string]: any;
}
0
```

### Expected Behaviour:

Expect that schema that cannot be compiled (due to lack of `id`/`title`) causes some error instead of just silent failure.

**Comment by bcherny** [comment]
We compile unnamed schemas, but it looks like we fail to infer a name for top-level schemas. We should infer the top-level schema name from the filename.

**Comment by bcherny** [comment]
Unable to repro. This is fixed.
