### ISSUE TITLE
Reference fails on schema for unknown reason

### ISSUE THREAD

**Issue by simonschllng** [bcherny/json-schema-to-typescript#22]
The following test fails for unknown reason: https://github.com/simonschllng/json-schema-to-typescript/commit/0140729000619c8e4090bfc120424489d20076d4

The TS references the schema file name instead of the type:

         [k: string]: any;
       }
       export interface Referencing {
         foo: ExampleSchema;
      -  bar?: geo;
      +  bar?: Geo;
       }

**Comment by bcherny** [comment]
@jcogilvie Do you know if this is caused by your commit?

**Comment by jcogilvie** [comment]
Until my commit, we weren't using referenced json files at all, so I think this is probably just additional work on top of mine. Possible it's a bug in the implementation but more likely just a case that wasn't in the test suite and didn't get considered.

**Comment by bcherny** [comment]
Sounds good - will look into it. Thanks @jcogilvie

**Comment by bcherny** [comment]
@simonschllng Interface names should be PascalCased - that is TypeScript convention. In your case, you need to PascalCase geo.json to Geo.json.

If there is more interest in preserving casing in the future, we can consider adding an exception for referenced schema names.

**Comment by simonschllng** [comment]
@bcherny this can only be considered a workaround. If you translate source to destination you can not rely on the source meeting destination's naming conventions. For now I can change it. As soon as you support using http refs, people might like to reference json-schema.org/geo or something else they are not able to rename.

**Comment by bcherny** [comment]
@simonschllng Good point about network schemas! The reason we automatically change name casing in some cases, is that by convention JSON-Schema property names are lowercased, while TS interface and type names are pascalcased.

We can either (1) always keep original casing, (2) keep original casing just for referenced schemas as a way to keep to convention as much as possible, or (3) also adjust casing for referenced schemas.

My vote is for (3). Filed https://github.com/bcherny/json-schema-to-typescript/issues/23 to track it.

**Comment by bcherny** [comment]
@simonschllng FYI this is fixed as part of 4.0.0. Sorry about the delay!
