### ISSUE TITLE
Unable to use within a react project

### ISSUE THREAD

**Issue by lostinpatterns** [bcherny/json-schema-to-typescript#224]
When importing the `compile` function from this package from a file in my react project, it's throwing `ReferenceError: require is not defined`

Anyone else had difficulty using this within a react project? It seems that the prettier dependency is trying to eval some require statements, which I assume babel is having trouble transpiling.

I'm interested in running `compile` at runtime from my app as JSON Schema are loaded via an API and then transforming them into ts types to use for validation, etc.

**Comment by chriskuech** [comment]
Can you elaborate about your scenario a bit more?  TypeScript is a static type system.  Why would you want to do this dynamically?

**Comment by lostinpatterns** [comment]
@chriskuech Yes, sorry! Opened this prematurely while investigating ways to generate some type-checking and data validation for a client that consumed an API that self-describes with JSON Schema before actually becoming familiar with Typescript. Closed.
