### ISSUE TITLE
Expose generator interface for custom output

### ISSUE THREAD

**Issue by geiseri** [bcherny/json-schema-to-typescript#234]
First off, this has saved me hours of work.  One thing that I need though is serializer support.  I currently use `ta-json` for the concrete implementations of my types.  This gives me a way to go back and forth with some comfort that I have a properly initialized object when using nested types.  They use decorators to denote their metainformation though.   So I have to copy-pasta each of my interfaces, extend and add the decorator.  This is a bit painful during development since I need to remember that step.  So what I am wondering is if there is a way to expose the final interface so that it can be post-processed.

Example:

```typescript
export interface IPerson {
  firstName: string;
  lastName: string;
  /**
   * Age in years
   */
  age?: number;
  family: Array<IPerson>;
}

@JsonObject()
export class Person implements IPerson {
    @JsonProperty()
    public firstName:string;

    @JsonProperty()
    public lastName:string;

    @JsonProperty()
    public age:number;

    @JsonProperty()
    @JsonElementType(IPerson)
    public family: Array<IPerson>;
}
```
I am not sure you are keen on adding `ta-json` as a dependency though, so if the final information for the interface could be returned as a structure adding custom concrete implementations would be very easy.

**Comment by bcherny** [comment]
Hey there @geiseri! Notice that JSTT is a modular compiler, where you can use any of the pieces as you like. Consider using it like so:

```
import { format } from 'json-schema-to-typescript/src/formatter'
import { generate } from 'json-schema-to-typescript/src/generator'
import { normalize } from 'json-schema-to-typescript/src/normalizer'
import { optimize } from 'json-schema-to-typescript/src/optimizer'
import { parse } from 'json-schema-to-typescript/src/parser'
import { dereference } from 'json-schema-to-typescript/src/resolver'
import { AST } from 'json-schema-to-typescript/src/types/AST'

let options = {...}

function myPostProcessor(ast: AST): AST {
  ...
}

function myCompile(schema: JSONSchema4, name: string) {
  return format(generate(
    myPostProcessor(optimize(
      parse(await dereference(normalize(schema, name), _options), _options)
    )),
    options
  ), options)
}
```

See https://github.com/bcherny/json-schema-to-typescript/blob/fcbe243e62df5722cda1cffa4049c3942d519f8b/src/index.ts#L110

I'm happy to accept a PR to extend the `AST` type and the `generate` function to support decorators, or any other valid TS node types.
