### ISSUE TITLE
Description with new lines `\n` are not output correctly in typescript comments

### ISSUE THREAD

**Issue by darcyparker** [bcherny/json-schema-to-typescript#24]
If I have a description like this in my JSON Schema:

```JSON
"description": "Some description\nWith multiple lines"
```

The output typescript definition neglects to comment the new lines too.

It would be great if long term, the description comment could support multiple lines. For the short term, I am simply stripping the new lines out of the JSON schema before I compile it to typescript.

**Comment by bcherny** [comment]
Not quite a duplicate of, but very similar to https://github.com/bcherny/json-schema-to-typescript/issues/10. Feel free to put up a PR, otherwise I will get to this eventually.

**Comment by darcyparker** [comment]
See https://github.com/bcherny/json-schema-to-typescript/pull/25

**Comment by darcyparker** [comment]
Please see new pull request: https://github.com/bcherny/json-schema-to-typescript/pull/26

**Comment by donaldpipowitch** [comment]
FYI: It would be nice to use `/** */` block comments for VS Code. See https://github.com/bcherny/json-schema-to-typescript/pull/26#discussion_r79550155.
