### ISSUE TITLE
7.0 generates any for simple schema.

### ISSUE THREAD

**Issue by kvandelden** [bcherny/json-schema-to-typescript#251]
v 6.1.3 generates

```
export interface IwbSource {
  SOURCE_ID?: string;
  SOURCE_NAME?: string;
  [k: string]: any;
}
```

v7 generates 

```
export type IwbSource = any;
```

Did the API change ?

**Comment by bcherny** [comment]
@bradzacher Mind taking a look when you have a chance, to see if it’s relates to your changes?

**Comment by bradzacher** [comment]
Hey @kvandelden - could you provide some more information?
What is the JSON Schema that is generating that?

The tests didn't change between versions (more tests were added), so you might have a case that has been missed, and isn't tested here.

Hard to say without seeing your schema.

**Comment by kvandelden** [comment]
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "IwbSource",
  "description": "Schema for Source records",
  "type": "object",
  "track": true,
  "properties": {
    "SOURCE_ID": {
      "type": "string"
    },
    "SOURCE_NAME": {
      "type": "string"
    },
    "BUSINESS_CONTACT": {
      "type": "string"
    },
    "TECHNICAL_CONTACT": {
      "type": "string"
    },
    "PARENT_SOURCE_ID": {
      "type": "string"
    },
    "CUSTOMER_SET_ID": {
      "type": "string"
    },
    "PRODUCT_SET_ID": {
      "type": "string"
    },
    "CONSUMPTION_PROVIDER_IND": {
      "type": "string"
    },
    "SHIPMENT_PROVIDER_IND": {
      "type": "string"
    },
    "TPM_IND": {
      "type": "string"
    },
    "LANGUAGE_DEFAULT": {
      "type": "string"
    },
    "CONSUMER_UOM": {
      "type": "string"
    },
    "STATISTIC_UOM": {
      "type": "string"
    },
    "SOURCE_CLIENT_ID": {
      "type": "string"
    },
    "WB_SOURCE_ID": {
      "type": "number"
    },
    "TIME_ZONE": {
      "type": "string"
    },
    "PRODUCT_GROUP_SET_ID": {
      "type": "string"
    },
    "RENDER_OPTIONS": {
      "type": "string"
    },
    "SOURCE_URL": {
      "type": "string"
    },
    "TREE_PATH": {
      "type": "string"
    }
  }
}

**Comment by kvandelden** [comment]
![image](https://user-images.githubusercontent.com/17126950/62734247-283dbb00-b9ee-11e9-91f9-d155d254033a.png)

This is the API I am calling..

**Comment by bradzacher** [comment]
I can't seem to repro this against master:

https://github.com/bradzacher/json-schema-to-typescript/commit/001e5f7731441ab898baf806f3888fab619a23e9

https://github.com/bradzacher/json-schema-to-typescript/blob/001e5f7731441ab898baf806f3888fab619a23e9/test/__snapshots__/test/test.ts.md#issue251js

**Comment by bcherny** [comment]
@bradzacher Thanks for taking a look so quickly, and sorry to pull you in on a hunch :)

@kvandelden I also can't repro this. I get the correct output:

```ts
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for Source records
 */
export interface IwbSource {
  SOURCE_ID?: string;
  SOURCE_NAME?: string;
  BUSINESS_CONTACT?: string;
  TECHNICAL_CONTACT?: string;
  PARENT_SOURCE_ID?: string;
  CUSTOMER_SET_ID?: string;
  PRODUCT_SET_ID?: string;
  CONSUMPTION_PROVIDER_IND?: string;
  SHIPMENT_PROVIDER_IND?: string;
  TPM_IND?: string;
  LANGUAGE_DEFAULT?: string;
  CONSUMER_UOM?: string;
  STATISTIC_UOM?: string;
  SOURCE_CLIENT_ID?: string;
  WB_SOURCE_ID?: number;
  TIME_ZONE?: string;
  PRODUCT_GROUP_SET_ID?: string;
  RENDER_OPTIONS?: string;
  SOURCE_URL?: string;
  TREE_PATH?: string;
  [k: string]: any;
}

```

Could you make a Github repo with a self-contained repro case, and comment back with a link to it?
