### ISSUE TITLE
[Question] Why dereference $refs when TypeScript allows for the same behavior?

### ISSUE THREAD

**Issue by erikfox** [bcherny/json-schema-to-typescript#260]
My team was using this library to successfully generate our TS typings until we introduced circular `$ref`s into our schema. When this library attempts to parse these circular `$ref`s, it breaks max call stack.

```js
// (node:30276) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
{
  "$id": "User",
  "type": "object",
  "properties": {
    "friends": {
      "type": "array",
      "items": {
        "$ref": "#/User" // circular!
      }
    }
  }
}
```

My question is why try to dereference `$ref`s at all when TypeScript supports references to other types/interfaces (including circular)?

```ts
// this is our expected output, and is totally legal in TS
interface User {
  friends: Array<User>
}
```

**Comment by qzb** [comment]
Actually, `json-schema-to-typescript` can easily handle schemas like this, but your reference is invalid. References in JSON Schema are relative to `$id`, so you have to change it from `#/User` to `#`. Additionally, if you want to have nicely named interfaces, you have to specify a title.

Schema after changes:
```json
{
  "$id": "User",
  "type": "object",
  "title": "User",
  "properties": {
    "friends": {
      "type": "array",
      "items": {
        "$ref": "#"
      }
    }
  }
}
```

Result:
```ts
export interface User {
  friends?: User[];
  [k: string]: any;
}
```

If you want to get rid index signature as well, you have to set `additionalProperties` to `false`.
