### ISSUE TITLE
Use fs from node instead of  normalize/mz

### ISSUE THREAD

**Issue by beckerei** [bcherny/json-schema-to-typescript#270]
Is it still needed to support older node version that don't support readFile, writeFile?

`mz` ships with a dependancy to `any-promise`.

Are you willing to accept a PR to use nodes own implementation

**Comment by bcherny** [comment]
Hey there @beckerei! We use `mz` for the Promises. Since native Promise-based APIs were introduced pretty recently in Node 10, I'd like to stick with `mz` for now to support whatever Node version people might be using. Is there a particular issue you're running into due to the dependency on `mz`?

**Comment by beckerei** [comment]
Prior I thought it we had [conflicts](https://jest-bot.github.io/jest/docs/troubleshooting.html#unresolved-promises) our test env, but then noticed the lib was not called during tests. So this was not an issue. Maybe others might have this problem at some point.
