### ISSUE TITLE
Add option to "import" referenced schemas

### ISSUE THREAD

**Issue by evergreen-lee-campbell** [bcherny/json-schema-to-typescript#276]
If I have the following schemas:

parent.json

```
{ 
    "title": "Parent",
    "properties": {
        "thing": {
            "$ref": "child.json"
        }
    } 
}
```

And child.json

```
{
    "title": "Child",
    "properties": {...}
}
```

It'd be really useful if the generated TypeScript file for "parent.d.ts" included an import for "child", based upon the reference path, e.g.:

```
import Child from './child'

export interface Parent {
    child?: Child;
}
```

This would greatly aid bulk compilation across a local schema ecosystem, without the code duplication of the TypeScript classes in all dependent files (I currently have a "Metadata" object exported by 14 different files in my codebase).

**Comment by evergreen-lee-campbell** [comment]
In other words, it's the ability _not_ to dereference.

**Comment by SomaticIT** [comment]
I would be very happy to have this feature!
Maybe I can help.

**Comment by johnbillion** [comment]
This seems to be a duplicate of #258.

**Comment by evergreen-lee-campbell** [comment]
You're absolutely right. I'll close in favour of #258.
