### ISSUE TITLE
Minor release to bump minimist

### ISSUE THREAD

**Issue by pavelvlasov** [bcherny/json-schema-to-typescript#285]
hey 👋

Is it possible to create a minor release in order to fix the security issue related to `minimist`?
`minimist` is already bumped in master so I guess it's just a matter of publishing it to npm.

Thanks for the awesome package!

**Comment by bcherny** [comment]
Published as part of 9.0.0.

1a91ef007cd7262331e81edc6a809777f5f38e4f
