### ISSUE TITLE
Performance improvement for `Default top level `id`` rule

### ISSUE THREAD

**Issue by thurst0** [bcherny/json-schema-to-typescript#286]
This [rule](https://github.com/bcherny/json-schema-to-typescript/blob/25f26c18ddbadab417567ab3004739f7da3b67d2/src/normalizer.ts#L57) is very slow to run when working with Large schemas.  

It is doing a stringify and equality on every traversed object or array element in the schema against the root schema just to figure out if it's the top level.  Really this rule only needs to run once for every schema.

I would recommend pulling it out of the rules `map` and running it one off in the `normalize` function.

Happy to contribute and open a PR for that, but wanted to float the idea.

**Comment by bcherny** [comment]
Good find! What if we have traverse pass an isRoot flag into each rule? If you want to implement that, I’ll be happy to stamp.
