### ISSUE TITLE
Prettier should be a peer dependency

### ISSUE THREAD

**Issue by NoxHarmonium** [bcherny/json-schema-to-typescript#288]
I'm having some issues with dependency resolution of `prettier` after installing this library.
In my project prettier is a "devDependency" and is pointing at "^2.0.2" to support the latest version of Typscript. 

This project has prettier as a regular dependency and is pointing at "^1.19.1". Depending on how I run my project, the version used by this library is selected and crashes as it cannot parse the newer version of Typescript that my project uses.

I think that prettier should probably be a peer dependency, so that the dependant project can choose the version of prettier that works for them. It would also let people opt out of prettier if they don't need that feature. 

There are also some "@types/*" packages that should probably be in the "devDependencies" section as they are not used at runtime.

Does changing prettier to a peer dependency make sense? If so, I'm happy to raise a PR.

Thanks!

**Comment by ycjcl868** [comment]
+ 1

**Comment by bcherny** [comment]
Would upgrading Prettier work as an alternative? It would be nice to avoid peerDeps if we can, so everything works out of the box as much as possible.

**Comment by bcherny** [comment]
Does #287 fix your issue?

**Comment by NoxHarmonium** [comment]
Thanks for doing that, yes that brings prettier up to a version that supports our project. It might get out of sync at a later point though but forcing the prettier version resolution using https://classic.yarnpkg.com/en/docs/selective-version-resolutions/ works for us.
