### ISSUE TITLE
unreachableDefinitions true does not always work as expected

### ISSUE THREAD

**Issue by awlayton** [bcherny/json-schema-to-typescript#289]
library version: 8..2.0

When I give the option `unreachableDefinitions: true`  I do not always get types output for my definitions.

I have a schema that is _only_ a set of definitions and when I compile it I do get types for all the definitions.
But I also have a schema which has definitions as well as having actual schema checks in the root schema and when I compile it only a type for the root schema is generated regardless of the value of `unreachableDefinitions` I use.

**Comment by bcherny** [comment]
Mind pasting your schema here? Tough to repro without it.

**Comment by awlayton** [comment]
I modified my schemas since and now I do not recall what I had that caused this issue. Sorry.
