### ISSUE TITLE
Webpack Failure

### ISSUE THREAD

**Issue by Lachee** [bcherny/json-schema-to-typescript#292]
Hello, when trying to use your library with webpack, I am getting the following error:

```
 ERROR in ./node_modules/json-schema-to-typescript/dist/src/index.js
    Module not found: Error: Can't resolve 'fs' in 'D:\apache\htdocs\mixy\node_modules\json-schema-to-typescript\dist\src'
     @ ./node_modules/json-schema-to-typescript/dist/src/index.js 56:11-24
     @ ./src/monaco/index.js

    ERROR in ./node_modules/json-schema-to-typescript/node_modules/prettier/index.js
    Module not found: Error: Can't resolve 'fs' in 'D:\apache\htdocs\mixy\node_modules\json-schema-to-typescript\node_modules\prettier'
     @ ./node_modules/json-schema-to-typescript/node_modules/prettier/index.js 5:27-40
     @ ./node_modules/json-schema-to-typescript/dist/src/formatter.js
     @ ./node_modules/json-schema-to-typescript/dist/src/index.js
     @ ./src/monaco/index.js

    ERROR in ./node_modules/json-schema-to-typescript/node_modules/prettier/third-party.js
    Module not found: Error: Can't resolve 'fs' in 'D:\apache\htdocs\mixy\node_modules\json-schema-to-typescript\node_modules\prettier'
     @ ./node_modules/json-schema-to-typescript/node_modules/prettier/third-party.js 11:25-38
     @ ./node_modules/json-schema-to-typescript/node_modules/prettier/index.js
     @ ./node_modules/json-schema-to-typescript/dist/src/formatter.js
     @ ./node_modules/json-schema-to-typescript/dist/src/index.js
     @ ./src/monaco/index.js

    ERROR in ./node_modules/json-schema-to-typescript/node_modules/prettier/third-party.js
    Module not found: Error: Can't resolve 'module' in 'D:\apache\htdocs\mixy\node_modules\json-schema-to-typescript\node_modules\prettier'
     @ ./node_modules/json-schema-to-typescript/node_modules/prettier/third-party.js 10:31-48
     @ ./node_modules/json-schema-to-typescript/node_modules/prettier/index.js
     @ ./node_modules/json-schema-to-typescript/dist/src/formatter.js
     @ ./node_modules/json-schema-to-typescript/dist/src/index.js
     @ ./src/monaco/index.js
```

This occurs when I try to build webpack bundles. I am packing your library into javascript bundles and plan to use it to convert a schema I have generated already, into typescript definitions for Monaco to auto suggest. Here is how I use it:
```
	/** Sets the schema suggestions for JSON */
	async setJsonSuggestions(schema) {
		compile = await import(/* webpackChunkName: "jstt" */ "json-schema-to-typescript");
		console.log("COmpile:", compile);

		ts = await compile(schema, 'settings');		
		console.log(schema, "=>", ts);
		monaco.languages.typescript.javascriptDefaults.addExtraLib(ts, 'js-schema.d.ts');
	}
```

While I am async loading it, I found even putting it at the top and bundling it within the same bundle doesn't work either. I havn't been able to test the code because webpack just fails while trying to bundle it.

I am not using any prior framework nor am I using node.js, as this is a custom PHP MVC framework, with webpack support.

Because I am putting the TS directly into Monaco, I dont actually need to use the prettier or compileFile. 

Here is a link to the entire repository if I have not provided enough information: 
https://github.com/Lachee/mixy/tree/json-options

**Comment by bcherny** [comment]
Hey there! Looks like Webpack doesn’t know about the fs module — you’ll need to tell it how to resolve it. You’ll want to Google for this, as it’s not related to this package.

Alternatively, consider using the already packaged version of this module that lives in /dist (make sure to install it using NPM).

Here’s an example of using JSTT in the browser: https://github.com/bcherny/json-schema-to-typescript-browser

**Comment by Lachee** [comment]
Thanks, I managed to fix this by first defining `fs` as a external and then defined the `prettier` as an external. In order to make it then work in the browser, I then added this little script to the start of the page as I did not care for formatting since it was being parsed by Monaco anyways:
```js
const prettier = {
        format(code, options) { 
            return code;
        }
    }
```

Thanks for the suggestion :)
