### ISSUE TITLE
reference known types as items for arrays / strings

### ISSUE THREAD

**Issue by dohomi** [bcherny/json-schema-to-typescript#297]
Hi Guys,

I'd like to open a feature request of referencing known types created by the compile function. Currently it is possible to reference enums as array/strings:
```js
"bloks": {
     "items":{
          "enum": ["Component1", "Component2", "Component3"], 
      }
      "type": "array"
} // =>   bloks?: ("Component1" | "Component2" | "Component3")[];
 // I'd like to archive following output:
//  bloks?: (Component1 | Component2 | Component3)[]
```
The referenced interface types are known/autogenerated. Hope this feature request make sense, thanks!

**Comment by bcherny** [comment]
To make sure I understand, what you're looking for is--

Given this input schema:

```json
{
  "properties": {
    "a": {
      "items": {
        "enum": ["X", "Y", "Z"]
      },
      "type": "array"
    }
  },
  "title": "S"
}
```

The output you're looking for is:

```ts
// Before
export interface S {
  a?: ("X" | "Y" | "Z")[];
  [k: string]: any;
}

// After
export type X = "X";
export type Y = "Y";
export type Z = "Z";
export interface S {
  a?: (X | Y | Z)[];
  [k: string]: any;
}
```

**Comment by dohomi** [comment]
@bcherny thanks for taking your time. I am looking for a solution where 
```
export interface S {
  a?: (X | Y | Z)[]; // these are interfaces built in the same file/time through external script
  [k: string]: any;
}
```
`X, Y, Z` they are known created in the same time/script. Inside interfaces have `blocks arrays` where they cross-referencing each other. So there should not be any validation, just the possibility to remove the `"` string annotation.

**Comment by bcherny** [comment]
I think you're looking for `tsType`. See example here: https://github.com/bcherny/json-schema-to-typescript/blob/master/test/e2e/customType.ts

**Comment by dohomi** [comment]
@bcherny yes you are totally right thanks for pointing me to the direction again
