### ISSUE TITLE
Support external (network) schema references

### ISSUE THREAD

**Issue by bcherny** [bcherny/json-schema-to-typescript#3]

**Comment by simonschllng** [comment]
Until then the error message in `index.ts:98` should be changed from:

          throw new Error("reference must start with #");

to

          throw new Error("external references (outside the json-schema file) are not supported");

**Comment by robertlong** [comment]
I recently found this package and needed external networked references support. I whipped up this script really quick and it seems to do the job for me.

https://gist.github.com/robertlong/3d5f771a992ff9374d64d92c95952674

It uses [json-schema-ref-parser](https://github.com/BigstickCarpet/json-schema-ref-parser) to combine the references into one giant JSON object and then compiles the whole file.

**Comment by bcherny** [comment]
@robertlong I was actually looking at using that package for json-schema-to-ts v2. Will give using it a shot - building ref resolution from scratch is hairier than it seems.
