### ISSUE TITLE
Duplicate declaration of extended schemas

### ISSUE THREAD

**Issue by jahredhope** [bcherny/json-schema-to-typescript#322]
This is an awesome tool. Thank-you very much for all the contributors work.

I wanted to raise an issue I'm seeing. I'm finding declations of extended types are being duplicated when I use `extends` but not when I use `allOf`.

I've documented a simplified working example and result I'm seeing in a GitHub repo.

Demo repo: https://github.com/jahredhope/demo-json-schema-extends-typescript

**Current behavior**
```ts
export interface Circle extends Shape {
  type?: "circle";
  radius?: number;
}
export interface Shape {
  type?: string;
  id?: string;
}
export interface Square extends Shape1 {
  type?: "square";
  height?: number;
  width?: number;
}
export interface Shape1 {
  type?: string;
  id?: string;
}
```

**Expected behaviour**
```ts
export interface Circle extends Shape {
  type?: "circle";
  radius?: number;
}
export interface Shape {
  type?: string;
  id?: string;
}
export interface Square extends Shape {
  type?: "square";
  height?: number;
  width?: number;
}
```

## Background

I've been trying out using `extends` with this tool to improve my generated types.

I'm a little confused as to whether `extends` is a current, previous or yet released part of the json-schema, but after finding out it was supported with this tool I gave it a go.

Unfortunatly my use-case would result in very large parts of my schema being duplicated a large number of times, so this duplication is a blocker for using `extends`.

**Comment by jahredhope** [comment]
This might be a duplicate of https://github.com/bcherny/json-schema-to-typescript/issues/193
However it does add a slightly different use-case so not sure if I should close it.

**Comment by bcherny** [comment]
Thanks for the report!
