### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by cmawhorter** [bcherny/json-schema-to-typescript#330]
i'm researching the various options out there and have pretty much landed on this lib but there is hardly a mention of how to handle validation.  i've found a few issues related to validation with regard to specific uses, but i was looking for a more general strategy/guidance.

json-schema-to-typescript translates json schema into type definitions. but then what?

do i need to ship both the raw json schema and type definitions? and at that point, is this how i should be doing validation below?

```ts
import * as Ajv from 'ajv';
import SomeJsonSchema from './schema/some.json';
import { SomeJsonType } from './generated-typings/some.ts';

const ajv = new Ajv();

const SomeValidator = ajv.compile(SomeJsonSchema);

export function ValidateSome(value: unknown): value is SomeJsonType {
  return SomeValidator(value);
}

function consumer(req) {
  if (ValidateSome(req.body)) {
    // req.body should be of type SomeJsonType
    runSomeTask(req.body);
  }
  else {
    console.log('validation errors', ValidateSome.errors);
  }
}

consumer();
```

if i'm missing something please let me know because that's a ton of boilerplate.  if i'm not missing something, what are the strategies people have been using to make this easier and less error prone?

**Comment by weasnerb** [comment]
I'm struggling with the same thing, however I did find this article that seems to help a bit: https://dev.to/tanepiper/validating-data-with-json-schema-angular-and-typescript-11dh

Hopefully this helps!

**Comment by cmawhorter** [comment]
thanks for posting. when you boil that all down though you're still trusting that using the schema matching id "customers" is actually the source schema you want to use.  

for example, perhaps it's a typo of a similar schema that will pass your tests but fail in production in subtle ways.  you're trusting that whoever typed in that id and file path were certain they matched.  

and that is my problem. i've yet to find a simple way to tightly couple json schema with typescript types that eliminates the possibility of me being dumb.  something that i am very often.

**Comment by weasnerb** [comment]
Ahh, I understand. I may run into a similar issue soon as well. Honestly I wish that there was an option to generate the typescript in the same folder structure as my schemata. I like to group my schemata by the module -> component -> schema-name.json. If they allowed the generated typescript files to be created in the same structure as their schema, then you could be sure you were working with the correct schema and typescript file if they are in matching folders.

**Comment by weasnerb** [comment]
Hey @cmawhorter, I just wrote a script tonight that uses quicktype to generate the typescript from my json schemas. It generates and saves the typescript files in the same folder as the schema. It would probably need some tweaking for your use, but if you are interested I could share the script.

**Comment by cmawhorter** [comment]
@weasnerb yeah, definitely, i'd love to see what you have!  and i'd not heard of quicktype before so thanks for that.

i found [typebox](https://github.com/sinclairzx81/typebox) which is interesting, but goes in the opposite direction. and of course still doesn't do validation.  but it at least unifies the type definition with a json schema.

i'm working on a fastify server right now and resorting to code generation because there are so. many. different. moving. parts to be able to define routes in a type safe way and keep them in sync with all the different json schema.

**Comment by bcherny** [comment]
Merging into #236
