### ISSUE TITLE
type of enums should not default to string

### ISSUE THREAD

**Issue by donaldpipowitch** [bcherny/json-schema-to-typescript#34]
See https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L251.

As far as I understand the standard it is allowed to create a schema like `{ enum: [ false ] }`. Currently an error is thrown if you use `{ enum: [ false ] }`: `TypeError: Enum was declared as a string type but found at least one non-string member`.

E.g. given

```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "foo": {
      "enum": [ false ]
    }
  }
}
```

and 

```
{
  "foo": false
}
```

is valid here: http://www.jsonschemavalidator.net/.

["understanding json schema"](https://spacetelescope.github.io/understanding-json-schema/reference/generic.html#enumerated-values) also says "You can use enum even without a type, to accept values of different types."

---

Okay, I see I can't even workaround this by using `{ type: 'boolean', enum: [ false ] }`, because of https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L257: `TypeError: Enum type must be string or integer; default is string if undefined`.

--- 

It is also valid to just use `false` as a type in TypeScript. See [this example](https://blogs.msdn.microsoft.com/typescript/2016/08/30/announcing-typescript-2-0-rc/):

```typescript
interface Success<T> {
    success: true;  // type is `true`, not `boolean`
    value: T;
}

interface Failure {
    success: false;  // type is `false`, not `boolean`
    reason: string;
}

type Result<T> = Success<T> | Failure;
```

**Comment by bcherny** [comment]
Fixed in 3773b2477c7ada189e5e476cf9bb305b320bd150.

I'm not sure that `foo: false` is valid - can you point me to some reference material?

**Comment by donaldpipowitch** [comment]
What do you mean? Well you can take the schema and payload given in the first post and try it in an online validator.

**Comment by bcherny** [comment]
```json
{
  "foo": false
}
```

Entering ^ in the validator you linked says that any value of `foo` is valid.

**Comment by donaldpipowitch** [comment]
I can't confirm that. For me, it looks like _only_ `false` is valid and everything else is invalid:

![image](https://cloud.githubusercontent.com/assets/1152805/18824331/9323a6e8-83c1-11e6-8437-2888d46952df.png)

![image](https://cloud.githubusercontent.com/assets/1152805/18824338/9fe447ca-83c1-11e6-97ee-1a2d0c823b9b.png)

![image](https://cloud.githubusercontent.com/assets/1152805/18824353/af0b20fc-83c1-11e6-84ff-55acecdade6a.png)

**Comment by bcherny** [comment]
We're talking about different things. In your example above,

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "foo": {
      "enum": [ false ]
    }
  }
}
```

This works as expected.

```json
{
  "foo": false
}
```

This is not valid JSON-Schema.

**Comment by donaldpipowitch** [comment]
> This is not valid JSON-Schema.

Why not? What is wrong? I can't spot an error.

**Comment by bcherny** [comment]
Ah, again we're misunderstanding each other. In the 2 code blocks in my comment above, you meant the 1st code block as the schema, the 2nd code block as the json to validate against that schema.

I thought you meant both as json schemas.

If that interpretation is correct, then your issue was fixed in the commit I linked above.

**Comment by donaldpipowitch** [comment]
Yeah, right. The left one (one the pictures) is the schema, the right one (`{ "foo": false }`) is the input JSON which is validated against the schema :)
