### ISSUE TITLE
Feature request: Emit unsupported JSON-Schema directives as code comments

### ISSUE THREAD

**Issue by Jarwain** [bcherny/json-schema-to-typescript#341]
Hi! I was just wondering if y'all had considered adding an option to support placing the schema properties "Not expressible in typescript" within comments/annotations for the project's property, a-la https://github.com/YousefED/typescript-json-schema

I think it would be a useful way of preserving useful attributes from the JSON Schema within the codebase. Supporting conversion between the two libraries would be neat as well.

**Comment by bcherny** [comment]
Hey, this is a great suggestion, which I think may be tracked somewhere already. Will leave this issue open for now.

If someone wants to take a stab at it, the first step would be to spec out what the output would look like for each unsupported JSON-Schema directive.

**Comment by bcherny** [comment]
Merged into #237
