### ISSUE TITLE
InvalidPointerError: Invalid $ref pointer. Pointers must begin with "#/"

### ISSUE THREAD

**Issue by Envek** [bcherny/json-schema-to-typescript#345]
I tried to use `json2ts` with complex schema which uses references to elements in another schema (see examples below), but got following error:

```
  code: 'EINVALIDPOINTER',
  message: 'Invalid $ref pointer "email". Pointers must begin with "#/"',
  source: '/home/envek/types.json',
  name: 'InvalidPointerError',
```

This probably caused by https://github.com/APIDevTools/json-schema-ref-parser/issues/42, also see https://github.com/APIDevTools/json-schema-ref-parser/issues/136

It (possibly) can be solved by https://github.com/APIDevTools/json-schema-ref-parser/pull/141 (I tried to [pull](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/checking-out-pull-requests-locally#modifying-an-inactive-pull-request-locally), rebase, and use it, but got stuck in TypeScript errors about JSONSchema4 vs JSONSchema6 incompatibilites).

**Steps to reproduce**:
<details>
<summary>person.json</summary>

```json
{
  "title": "Example Schema",
  "type": "object",
  "properties": {
    "fullName": {
      "type": "string"
    },
    "emailAddress": {
      "allOf": [{ "$ref": "types.json#email" }]
    }
  },
  "additionalProperties": false,
  "required": ["fullName", "emailAddress"]
}
```
</details>
<details>
<summary>types.json</summary>

```json
{
  "$id": "https://example.com/example.json",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "types": {
    "email": {
      "$id": "#email",
      "type": "string",
      "format": "email"
    }
  }
}
```
</details>

```sh
json2ts person.json
```

**Expected result**:
<details>
<summary>person.d.ts</summary>

```ts
export interface ExampleSchema {
  fullName: string;
  emailAddress: string;
}
```
</details>

**Any workarounds?**

Is there a way to workaround this? Real schemas I want to process are huge and full of such `$id`-references…

**Comment by bcherny** [comment]
Thank you for the report + investigation. Mind filing this in the json-schema-ref-parser repo, and comment back when the fix has been merged so we can upstream it here?
