### ISSUE TITLE
Is this repo dead ?

### ISSUE THREAD

**Issue by fredericbarthelet** [bcherny/json-schema-to-typescript#347]
Thanks for the amazing work done in this package.

I'm currently using it to generate [Serverless framework](https://github.com/serverless/serverless) typescript definition in https://github.com/serverless/typescript. I encountered a few issues, where the community offered to participate in (like https://github.com/bcherny/json-schema-to-typescript/issues/343, https://github.com/bcherny/json-schema-to-typescript/issues/243) but where no maintainer of this repository replied.

Looks like this repo **has not been maintained since July** - 102 opened issues. In order to solve those issues, and also to benefit this community, @bcherny **are you planning on continuing maintenance of this repository ? And if not, is there a community maintained fork of this repository already available where all these issues could be fixed ?**

**Comment by bcherny** [comment]
Hey there! This repo is not dead, but I do not have time to give it the attention it deserves. I try to comb through issues/PRs every few months, which is definitely a cadence that leaves much to be desired.

Contributions are welcome, and I've added comments to the two issues you linked. If someone wants to co-own this repo, contributing + code reviewing is a great place to start!

**Comment by fredericbarthelet** [comment]
Thanks for your reply @bcherny :) Glad to hear you're still working on this.
I'll give a go at #343 !
