### ISSUE TITLE
Root $ref fails to validate

### ISSUE THREAD

**Issue by isaacl** [bcherny/json-schema-to-typescript#349]
```json
{
  "$ref": "#/definitions/EmailConfig",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "EmailConfig": {
      "additionalProperties": false,
      "properties": {
        "adminContact": {
          "type": "string"
        }
      }
    }
  }
}
```
is valid (in fact is part of the [test suite here](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/2019-09/tests/draft7/ref.json#L122-L129)).  But this library fails to convert.

**Comment by bcherny** [comment]
Thanks for the report. This seems to be a bug with json-schema-ref-parser. Mind filing an issue (or submitting a fix) in that repo, and commenting back here when it's resolved so we can upstream it? Thanks!
