### ISSUE TITLE
[10] Broken generation when using multiple types and default value

### ISSUE THREAD

**Issue by wszydlak** [bcherny/json-schema-to-typescript#352]
Invalid types are generated when using multiple types for property, eg:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "my-schema",
    "type": "object",
    "properties": {
        "example": {
            "type": ["boolean", "string"],
            "default": true
        }
    },
    "additionalProperties": false
}
```

We get interface:

```ts
export interface MySchema {
  example?: boolean & (boolean | (boolean & string));
}
```

Field **example** is treated by typescript as `boolean | undefined` but should be `boolean | string | undefined`.
It's something connected to **default** keyword, ommiting default value generates correct interface:

```ts
export interface MySchema {
  example?: boolean | string;
}
```

This is regression, in version 9 it was working.

**Comment by bcherny** [comment]
Fixed 10.0.1.
