### ISSUE TITLE
Export enum name to allow for casting

### ISSUE THREAD

**Issue by PerttiK** [bcherny/json-schema-to-typescript#354]
The following JSON schema
```
"fruit": {
      "description": "type of fruit",
      "type": "string",
      "enum": [
        "BANANA",
        "KIWI",
        "CHERRY
      ]
    }
```
is converted to 
```
fruit: "BANANA" | "KIWI" | "CHERRY"
```
in the generated interface.

That looks good, but this means you can't assign a string (even when the string is "BANANA", "KIWI" or "CHERRY") to an object that adheres to the interface, unless you cast it. However, without the d.ts file exporting the enum type there's no way you can actually cast the string to the enum.
The problem can be solved when json-schema-to-typescript would export the enum as follows
```
export enum fruit {
  BANANA = "BANANA",
 KIWI = "KIWI",
 CHERRY = "CHERRY"
}
```
because that would allow consumers of the interface to cast a string to the enum as follows
```
...
fruitPropertyOfObjectThatShouldAdhereToInterface: <fruit> fruitString,
...
```

Am I missing something or would this be a much needed improvement?

**Comment by PerttiK** [comment]
This is similar to https://github.com/bcherny/json-schema-to-typescript/issues/337 except for the suggestion to not even have to rely on propertyNames

**Comment by bcherny** [comment]
You can do this with `tsEnumNames`:

**Input**:

```json
{
  type: 'object',
  properties: {
    fruit: {
      description: 'type of fruit',
      type: 'string',
      enum: ['BANANA', 'KIWI', 'CHERRY']
    },
    fruit2: {
      description: 'type of fruit',
      id: 'Fruit',
      type: 'string',
      enum: ['BANANA', 'KIWI', 'CHERRY'],
      tsEnumNames: ['BANANA', 'KIWI', 'CHERRY']
    }
  },
  required: [],
  additionalProperties: true,
}
```

**Output**:

```ts
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Demo {
  /**
   * type of fruit
   */
  fruit?: "BANANA" | "KIWI" | "CHERRY";
  fruit2?: Fruit;
  [k: string]: unknown;
}

/**
 * type of fruit
 */
export enum Fruit {
  BANANA = "BANANA",
  KIWI = "KIWI",
  CHERRY = "CHERRY"
}
```

Adding a new option to generate string enums instead of unions (without needing `tsEnumNames`) seems reasonable too, if more folks want this.

**Comment by PerttiK** [comment]
I think it's a really important principle not to have to rely on custom properties in your input JSON schema to end up with an exported named enum in TypeScript that you can use for casting your strings when coding.
As mentioned before this is similar to #337 and actually exactly the same as #200 with 6 upvotes and a pull request that was never merged (https://github.com/bcherny/json-schema-to-typescript/pull/262)

**Comment by bcherny** [comment]
Sounds good, thanks for the feedback @PerttiK.

I've reopened #200, and am marking this issue as a dup. Feel free to resurrect #262 if you'd like.
