### ISSUE TITLE
Reusing type definitions causes errors in v10

### ISSUE THREAD

**Issue by Linksku** [bcherny/json-schema-to-typescript#355]
I just updated from v9 to v10, but I'm getting `TypeError: Cannot redefine property: Symbol(Parent)`. I'm reusing schemas like this:

```
const idSchema = { type: 'integer', minimum: 1 };

jsonSchema = {
  type: 'object',
  properties: {
    id: idSchema,
    userId: idSchema,
  },
};
```

This error goes away if I add `configurable: true` to `Object.defineProperty` in `linker.js`. Not sure if this is the correct fix.

**Comment by bcherny** [comment]
Hey, thanks for the report. Can you whittle down your JSON Schema to the minimal case that reproduces this error, and paste it here?

**Comment by Linksku** [comment]
Updated the original post. The error goes away when I don't reuse `idSchema`, i.e.:

```
jsonSchema = {
  type: 'object',
  properties: {
    id: { type: 'integer', minimum: 1 },
    userId: { type: 'integer', minimum: 1 },
  },
};
```

**Comment by lomboboo** [comment]
can confirm the same on my end

**Comment by bcherny** [comment]
Just tried to repro this, can't repro it locally.

What environment are you running into this issue in (node? browser? if so, what version?), and how exactly are you invoking JSON Schema To TypeScript (command line? `compile` function)?

**Comment by bcherny** [comment]
Mind installing the latest version (10.0.1) and reporting if you're still hitting this issue?

**Comment by lomboboo** [comment]
@bcherny Hi, sorry for late response. Looks like it is working now. Tested with 10.0.2

**Comment by paul-em** [comment]
Had the issue as well. Looking good now! Thank you!

**Comment by Linksku** [comment]
Thanks for fixing this!
