### ISSUE TITLE
Question: `!` applied at end of array property

### ISSUE THREAD

**Issue by darcyparker** [bcherny/json-schema-to-typescript#39]
This syntax is new to me:
https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L260

I see is used frequently in this src, but I don't understand the idiom or syntax and can't find reference to it  in typescript's documentation.

Can you give me some pointers?

Thanks

**Comment by darcyparker** [comment]
(I can tell it has something to do with the possibility that value is undefined...)

**Comment by bcherny** [comment]
It's usually a sign that you're doing something wrong.

See https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#non-null-assertion-operator

**Comment by darcyparker** [comment]
Thanks for the reference. Good to know for when I don't have time to refactor code.
