### ISSUE TITLE
has any solution to reduce the size of package

### ISSUE THREAD

**Issue by Jcanno** [bcherny/json-schema-to-typescript#399]
I‘am trying import `json-schema-to-typescript` to my chrome extension project in the browser, but bundle size grows obviously. Has any solution to reduce the size of package? I just only use one `complie` api in my sense.

import before:
<img width="1021" alt="before" src="https://user-images.githubusercontent.com/34361691/121349472-229fbc00-c95c-11eb-9021-5193217cf1c7.png">

import after:
<img width="1131" alt="after" src="https://user-images.githubusercontent.com/34361691/121349522-32b79b80-c95c-11eb-8106-14584346f535.png">

**Comment by PowerSupply** [comment]
How did you solve this?
