### ISSUE TITLE
Support URN id references

### ISSUE THREAD

**Issue by mikaello** [bcherny/json-schema-to-typescript#406]
**Feature request.**

It seems that JSON Schemas with references built with URN is not supported, e.g. these schemas:

* [github.com/phenopackets/phenopacket-format/schema/condition-schema.json](https://github.com/phenopackets/phenopacket-format/blob/3f4f024b869af5c80314fb12dfe513d80ab30cf9/schema/condition-schema.json)
* [github.com/orienteering-oss/iof-orienteering-data-schemas/iof_v3_schema.json](https://github.com/orienteering-oss/iof-orienteering-data-schemas/blob/39d93bed6b8afa9797218fe2c2151ef710da67c3/iof_v3_schema.json)

When trying to convert these to TS, the following error messages are produced:

```shell
$ cat condition-schema.json | json2ts
[
  {
    message: 'Error opening file "urn:jsonschema/:org:phenopackets:api:model:ontology:OntologyClass" \n' +
      "ENOENT: no such file or directory, open 'urn:jsonschema/:org:phenopackets:api:model:ontology:OntologyClass'",
    source: 'urn:jsonschema/:org:phenopackets:api:model:ontology:OntologyClass',
  }
]
```

and

```shell
$ cat iof_v3_schema.json | json2ts
[
  {
    message: 'Error opening file "urn:jsonschema/:iof:v3:Country" \n' +
      "ENOENT: no such file or directory, open 'urn:jsonschema/:iof:v3:Country'",
  }
]
```

**Comment by bcherny** [comment]
Please file this in https://github.com/APIDevTools/json-schema-ref-parser

**Comment by mikaello** [comment]
> Please file this in https://github.com/APIDevTools/json-schema-ref-parser

Done: https://github.com/APIDevTools/json-schema-ref-parser/issues/263
