### ISSUE TITLE
Why not parse?

### ISSUE THREAD

**Issue by cawa-93** [bcherny/json-schema-to-typescript#41]
[Source JSON](https://github.com/VKCOM/vk-api-schema/blob/master/objects.json)
**My code**
```
const converter = require('json-schema-to-typescript');
var fs = require('fs');
converter.compileFromFile('./vk-api-schema/objects.json')
	.then(function (interf) {
		fs.writeFile("./types/objects.d.ts", interf);
	});
```
**Result:**
```
export type Objects = any;
```

**Comment by darcyparker** [comment]
The referenced source JSON has `definitions` but no properties that reference these definitions. See https://github.com/json-schema-org/json-schema-spec/blob/master/schema.json as an example of a schema with definitions that are referenced in the properties.

BTW: I get the same result and `ajv` (https://github.com/epoberezkin/ajv) compiles the following: (Notice the validator always returns `true` which agrees with `export type Objects = any;`

```js
// ======================================================================
//  Generated JSON validate for: "objects" JSON object
// ======================================================================
//           JSON Schema Source: json-schema/data-api/v1/objects.json
//          sha1 of JSON Schema: 8eee6d2eed1a1f3ddaaaae2281b54d20da2a9e0b
//            Validate Compiler: ajv v4.7.4
// ======================================================================
/* jshint ignore: start */
/* eslint-disable */
module.export = function validate (data, dataPath, parentData, parentDataProperty, rootData) {
  'use strict';
  if (rootData === undefined) rootData = data;
  validate.errors = null;
  return true;
}
```

> Note, I added my own custom header to `ajv` output. But I don't touch the compiled validator

**Comment by cawa-93** [comment]
@darcyparker in repository are this file - [schema.json](https://github.com/VKCOM/vk-api-schema/blob/master/schema.json); This can help?

**Comment by darcyparker** [comment]
@cawa-93 - I may not be understanding your problem...

I compiled the `schema.json` and get the following
> *  It seems to agree with what I read in the schema. 
> * Perhaps you are expecting it to parse some definitions from the other files?   
>    * If so, I think you need to create a schema that references these definitions.  
>    * My initial look at the JSON schemas is that they have many definitions but they aren't referenced outside of the definitions scope.  (I think the definitions are meant to be referenced by other JSON schema.)

```typescript
export interface Error {
  /**
   * Error name
   */
  name: string;
  /**
   * Error code
   */
  code: number;
  /**
   * Error description
   */
  description: string;
}
/**
 * Parameter type
 */
export type ParameterTypes = "array" | "boolean" | "integer" | "number" | "string";
export type ItemTypes = "boolean" | "integer" | "number" | "string";
export interface Parameter {
  /**
   * Parameter name
   */
  name: string;
  /**
   * Parameter type
   */
  type: ParameterTypes;
  items?: {
    type: ItemTypes;
    maximum?: number;
    minimum?: number;
  };
  maxItems?: number;
  minItems?: number;
  maximum?: number;
  minimum?: number;
  enum?: any[];
  default?: any;
  required?: boolean;
  maxLength?: number;
  minLength?: number;
  /**
   * Parameter description
   */
  description?: string;
}
export interface Method {
  /**
   * Method name
   */
  name: string;
  /**
   * Method description
   */
  description?: string;
  /**
   * Is it open method
   */
  open?: boolean;
  /**
   * Input parameters for method
   */
  parameters?: Parameter[];
  /**
   * References to response objects
   */
  responses?: Object;
  /**
   * Possible errors
   */
  errors?: Error[];
}
/**
 * API declaration
 */
export interface Ischema {
  /**
   * Possible errors
   */
  errors?: Error[];
  methods?: Method[];
}
```

**Comment by cawa-93** [comment]
@darcyparker, you says:

> I suspect your objects.json is intended to be referenced by other schemas because it doesn't define properties for itself.
I suggested that perhaps `schema.json` - this is it.
Unfortunately I am not a developer of the scheme. I just wanted to use it in his TypeScript

**Comment by darcyparker** [comment]
Good luck with it. I can empathize with the process of transforming the JSON schemas to typescript interface definitions and validators.

I was thinking about your examples a little more. The compiler is doing its job of creating an interface definition in typescript for the JSON schema.  But there could situations where it would useful to have interface definitions for JSON schema definitions that aren't actually used by the current JSON schema.  Perhaps the compiler could pre-emptively create typescript interface definitions for each definition in the JSON schema definitions block.  And then, as they are used, reference them... and if they aren't used (yet) you will have them for future use.  I have no need for this yet... but it might be worth writing a ticket if/when you or someone else has the need.

**Comment by wiktor-k** [comment]
Sorry for reviving this old thread but I had the same need - to generate TypeScript interfaces for nested types inside `definitions`. Fortunately it's easy to do with `compile` and some glue code:

```ts
import { compile } from 'json-schema-to-typescript'

import { readFileSync } from 'fs';

const schema = JSON.parse(readFileSync('schema.json', 'utf8'));

for (const name in schema.definitions) {
    // name is the key in definitions map that is used as an interface name
    schema.definitions[name].title = name;
    console.log(compile(schema.definitions[name]));
}
```

Maybe the example above will be useful for someone.
