### ISSUE TITLE
Set Default Working Directory to Schema Root

### ISSUE THREAD

**Issue by HunterKohler** [bcherny/json-schema-to-typescript#417]
## Set Default Working Directory to Schema Root

References should be resolved by the directory of the schema itself, not the script/program caller. Currently, the cwd is resetting on every de-reference, thus making it *virtually* impossible to compile multi-file schemas without first de-referencing them with the `$RefParser` library. This ruins the ability to reuse *definition* interfaces, and bloats code. Either way, defaulting to schema root would conform with the *RFC*, trivially.

I don't think this should be too difficult to change because the $RefParser library does this by default.

## Example of Issue *(exposition)*:

Assume a working tree like the following.
```
schemas
├── bits
│   ├── review_partial.json
│   └── user_partial.json
├── helpers
│   ├── object_id.json
│   └── tokens_wrapper.json
├── review.json
└── user.json
```

And the file `schemas/bits/review_partial.json` being:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object"
    "properties": {
        "_id": { 
            "$ref": "../helpers/object_id.json"
        }
    }
}
```

And the file `schemas/helpers/object_id.json` being:
```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "properties": {
        "wrapper": {
            "$ref": "./tokens_wrapper.json",
        }
    }
}
```

1. Invoking the compiler on `schemas/bits/review_partial.json` outside the directory (say, at the root), will not result in a schema-relative reference.
2. If you change the `cwd` setting to `schema/bits`, this initial reference will resolve, but the reference in `schemas/helpers/object_id.json` will ALSO resolve with `cwd` of `schemas/bits`, which, it isn't in, and thus the reference fails to resolve to `schemas/helpers/token_wrapper.json`

## `$RefParser` Library

Note that the parser will auto resolve based on the schema root if invoked on the file. Take the last example: by default, the following will bundle the schema. This is required before passing it to this library, which, as I said ruins the possibility of interface definition re-use, and makes it much more difficult to invoke, especially without experience with JSON references.

```js
console.log(await $RefParser.bundle("./schemas/bits/review_partial.json"));
// logs bundled schema without error
```

**Comment by relief-melone** [comment]
I think this is the same issue as #324 no? If yes I created a pull Request https://github.com/bcherny/json-schema-to-typescript/pull/421 unfortunately there has no review been made so far but you could try if this solves your problems. It does solve ours when it comes to references ;)

**Comment by relief-melone** [comment]
since at least at the moment this repo seems to be abandonden and my pr has been lying around for 2 months i decided to publish my fork (will deprecate it as soon as the $ref issues get resolved in this repo). Let me know if this fixes your issue as well. 
https://www.npmjs.com/package/rm-json-schema-to-typescript

**Comment by beuleal** [comment]
Hey @relief-melone - Do you know if the same works for CLI? I'm trying to `json2ts -i myschema.json` for my current schema that references an external schema:
```
"items": {
            "$ref": "file://another_schema.json#/definitions/myItem"
          }
```

This is not working. I'm receiving the following error:
```
code: 'ERESOLVER',
    message: 'Error opening file "/another_schema.json/" \n' +
      "ENOENT: no such file or directory, open '/another_schema.json/'",
```

**Comment by relief-melone** [comment]
sorry for the late reply. i am using it in the cli. I published my fork under 
[rm-json-schema-to-typescript](https://www.npmjs.com/package/rm-json-schema-to-typescript)

and will deprecate if this fix has been implemented in the main branch. however for us this was the only way to go for now. You should be able to install and use it in the same way. Please give me some feedback if it works as you expect it to.

**Comment by bcherny** [comment]
Dup of https://github.com/bcherny/json-schema-to-typescript/issues/324.

Sorry for the delayed response. Feel free to update the PR per requested changes!
