### ISSUE TITLE
json2ts $ref (again) some clarification is needed

### ISSUE THREAD

**Issue by pkej** [bcherny/json-schema-to-typescript#425]
I'm a bit stumped. I've tried to set the following for the json2ts commandline:

```cli
json2ts -i schemas/ -o types/
```
In my $ref inside the json I've set the following:
```json
"$ref": "/schemas/commands/command.json"
```
This resolves to E:/schemas/commands/command.json which doesn't exist. Instead I have to add the arbitrary path from my E: drive down through all the intermediary folders into my project, so something like this:

```cli
/e/projects/myown/javascript/myjson2tsproject/schemas/commands/command.json
```
That doesn't seem right at all, since all my schemas will be in the folder /schemas when deployed on e.g. "https://localhost/".

I've tried the --cwd="/c/", but it doesn't seem to be set anywhere in the code, nor does it seem to change anything, I get the same error messages as if cwd does nothing.

Running this on json without any external refs works well.

After reading some discussions in other issues I got the impression that one is supposed to use ".." to go up an level. I've tried that as well, but it doesn't work, and frankly, it seems wrong since [this states]():

> The URI-references in $ref resolve against the schema’s Base URI (https://example.com/schemas/customer) which results in https://example.com/schemas/address. The implementation retrieves that schema and uses it to evaluate the “shipping_address” and “billing_address” properties.

Which is also how it would work in HTML. I'm therefore wondering how to use json2ts and how to use the command line?

**Comment by bcherny** [comment]
Please ask in https://github.com/APIDevTools/json-schema-ref-parser -- we outsource ref resolution to the json-schema-ref-parser package. Thanks!
