### ISSUE TITLE
`declareExternallyReferenced` not working? 

### ISSUE THREAD

**Issue by jlorince** [bcherny/json-schema-to-typescript#437]
Either I don't understand `declareExternallyReferenced`, or it's not working as expected. My expectation is that it wouldn't even try processing an external referenced schema. Here's a minimal example:

```
  const schema = {
    properties: {
      vegaSpec: { $ref: "https://vega.github.io/schema/vega-lite/v4.json" },
    },
    type: "object",
  } as JSONSchema4;
  compile(schema, "Schema", {
    declareExternallyReferenced: false,
  })
    .then((ts) => fs.writeFileSync("generated/schemaTypes.d.ts", ts))
    .catch((err) => console.error(err));
```

This errors with: 
```
Error: Refs should have been resolved by the resolver! {
   ...A ton of properties from the externally referenced schema
  '$ref': '#/properties/vegaSpec'
}
    at parseNonLiteral (/Users/jlorince/git/hex/node_modules/json-schema-to-typescript/dist/src/parser.js:159:19)
    at parseAsTypeWithCache (/Users/jlorince/git/hex/node_modules/json-schema-to-typescript/dist/src/parser.js:70:31)
    at parse (/Users/jlorince/git/hex/node_modules/json-schema-to-typescript/dist/src/parser.js:29:21)
    at /Users/jlorince/git/hex/node_modules/json-schema-to-typescript/dist/src/parser.js:281:14
    at /Users/jlorince/git/hex/node_modules/lodash/lodash.js:3585:27
    at /Users/jlorince/git/hex/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/Users/jlorince/git/hex/node_modules/lodash/lodash.js:3032:24)
    at /Users/jlorince/git/hex/node_modules/lodash/lodash.js:4936:18
    at baseMap (/Users/jlorince/git/hex/node_modules/lodash/lodash.js:3584:7)
    at Function.map (/Users/jlorince/git/hex/node_modules/lodash/lodash.js:9622:14)
```

Any idea what's going on here? We don't maintain this external schema, so I can't guarantee there aren't issues with it, but I would assume that by setting `declareExternallyReferenced` to `false`, it shouldn't even try to parse that schema?

**Comment by bcherny** [comment]
Hey there, sorry for the delayed response!

`declareExternallyReferenced` controls whether externally referenced JSON Schemas are *emitted* as TypeScript code. What you seem to be looking for is to skip *resolving* external schemas.

To do that, you can use `$refOptions`:

```ts
compile(..., ..., {
  $refOptions: {
    resolve: {
      external: false
    }
  }
}
```

We use the external [json-schema-ref-perser](https://github.com/APIDevTools/json-schema-ref-parser) package to resolve `$ref`s, so check out that repo to see available options.

That said, what output would you expect with unresolved `$ref`s (examples would help)? If you want to do something custom, you might consider using json-schema-ref-perser's `$refOptions.resolve.file` or `$refOptions.resolve.http` to resolve to empty JSON Schemas, or whatever you'd like your output to be.
