### ISSUE TITLE
Why does it mutate the original schema object?

### ISSUE THREAD

**Issue by GabenGar** [bcherny/json-schema-to-typescript#443]
Just `console.log(JSON.stringify(obj))` before and after compilation and see it getting `id` property with the `name` value which was passed to it.

**Comment by bcherny** [comment]
This is for performance, to avoid cloning large objects in memory.

For sure a bit of an annoyance (when JSTT started, we didn't mutate -- this was added later). 

Is this causing any specific issues for you?

**Comment by GabenGar** [comment]
Yes, I pass a collection of schemas around to generate the code. Because `id` is slapped by this module `ajv` crashes with cryptic errors don the line. Took me a while to debug.
Not sure this package needs to care about performance that much considering "runtime interfaces" is not a thing.

**Comment by bcherny** [comment]
Published as part of v11.0.0.
