### ISSUE TITLE
Add ability to format output

### ISSUE THREAD

**Issue by bcherny** [bcherny/json-schema-to-typescript#45]
Options:

- https://github.com/prettier/prettier/issues/13
- https://github.com/vvakame/typescript-formatter
- https://github.com/palantir/tslint/issues/561
- https://github.com/nojvek/tslint-fix
- http://clang.llvm.org/docs/ClangFormat.html

**Comment by darcyparker** [comment]
FYI: I filed a request for option to define `quotemark` for pretty printer here: https://github.com/Microsoft/TypeScript/issues/11320

**Comment by alexburner** [comment]
Hi, I happen to be wandering the web looking for a good typescript autoformatter. FWIW I've seen another option that could be added to your list, `clang-format` also supports JS/TS. I haven't fully tested this for myself.

Learned it here https://github.com/Microsoft/vscode/issues/9514#issuecomment-294911838

**Comment by bcherny** [comment]
@alexburner Added it to the list - thanks! On first impression it looks very powerful. Does it support outputting with no semicolons? I couldn't find an option searching through the docs.

**Comment by alexburner** [comment]
@bcherny happy to share! I'm afraid I haven't had a chance to dive in yet, was just in the research phase and got pulled into some defect tickets ;) I will be digging further soon, I'll let you know if I run across anything for semicolons.

I can say:
- the angular team appears to use it, and has created a well-maintained npm module: https://github.com/angular/clang-format
- there's a good list of formatting options here, but no mention of semicolons: http://clang.llvm.org/docs/ClangFormatStyleOptions.html
