### ISSUE TITLE
How hard would it be to generate Python?

### ISSUE THREAD

**Issue by jmcguire** [bcherny/json-schema-to-typescript#457]
I'm trying to gauge how much work it would be. I'm working on a Node project that does code generation, and I'm already using this library for the Typescript portion. (And I can't find any JSON Schema -> Python libraries on npm.)

Can I do with with only touching **generate.ts**, and turning off prettier? Are Typescript idioms deeply entwined in the rest of the code base?

I don't know if this is the right place to ask, but it does seem like the place with the most number of experts to yell at me.

**Comment by bcherny** [comment]
This is an interesting idea! If you wanted to pursue this, a path could be to:

1. Prototype a new Python `generator.ts`
2. Split out json-schema-to-typescript into json-schema-to-ast and json-schema-ast-to-typescript, or something (I can help with this)
3. Publish your new json-schema-to-python project
