### ISSUE TITLE
ignoreMinAndMaxItems should check if schema is an array

### ISSUE THREAD

**Issue by mastercoding** [bcherny/json-schema-to-typescript#458]
My schema currently fails if I enable the config ignoreMinAndMaxItems, because the rule doesn't check if the schema is actually an array type before attempting to find 'minItems' in schema:

```
TypeError: Cannot use 'in' operator to search for 'maxItems' in .autocomplete#required
```

The fix is trivial (checking for isArrayType(schema)) and I will attach a PR to this issue.

**Comment by mastercoding** [comment]
Never mind, seems to fixed in master...

**Comment by mastercoding** [comment]
My apologies for the spam, but could you release a new version with this fix?

**Comment by bcherny** [comment]
Yup, new release coming soon. Just trying to sneak in a couple more breaking fixes before the major version bump.

Feel free to install from master for now, if you like.
