### ISSUE TITLE
Please publish latest to npm to update dependencies

### ISSUE THREAD

**Issue by justin-fiedler** [bcherny/json-schema-to-typescript#462]
Hello, thanks for the great library.

Unfortunately the latest published package is using an older version of prettier `^2.2.0` which is causing failures in our monorepo CI as other modules use a newer version `^2.6.2`, but the older version ends up being installed & used.

I see that you have [already updated the prettier dependencies in the repo on May 15](https://github.com/bcherny/json-schema-to-typescript/commit/8b3267fcf264e218699122703d63cbffda1c7801).

Could you please publish the latest version of the library to NPM?

Thanks!

**Comment by bcherny** [comment]
Published as part of v11.0.0.
