### ISSUE TITLE
Error Installing v11.0.0 With Yarn

### ISSUE THREAD

**Issue by spencerbeggs** [bcherny/json-schema-to-typescript#465]
When installing with Yarn 3, I receive:

```
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: @apidevtools/json-schema-ref-parser@https://github.com/bcherny/json-schema-ref-parser.git#984282d3: Couldn't resolve "984282d3" as either a commit, a tag, or a head - if a commit, use the 40-characters commit hash
```

This appears to be due to [this line of code in package.json](https://github.com/bcherny/json-schema-to-typescript/blob/master/package.json#L49).

**Comment by tillkolter** [comment]
The git dependency is in general far from ideal. I hope [this pull request](https://github.com/APIDevTools/json-schema-ref-parser/pull/272) will be merged soon.

**Comment by spencerbeggs** [comment]
Thanks for the quick fix!
