### ISSUE TITLE
Bug: the JSONSchema4 `extends` type is inconsistent with the actual use

### ISSUE THREAD

**Issue by halo951** [bcherny/json-schema-to-typescript#467]
# version
10.1.5

# scene
I have a scene that require use `extends` generate interface. however, after I pass in `extends` according to the type of JSONSchema4, the parser cannot resolve the attribute of 'extends', and throw an exception.

# example 

```typescript
const json2ts = require('json-schema-to-typescript')

const res = await json2ts.compile(
        {
            extends: ['IResponse'], // tpye is JSONSchema4 extends
            type: 'object',
            additionalProperties: false,
            properties: {
                Result: {
                    type: 'string'
                }
            }
        },
        'ITest',
    )
```

# debug error message
> the output is missing `IResponse` 
```
export interface Aefw extends  {
    Result?: string
}
```
.
Then, I checked the document and found that the parser actually uses the higher version of jsonschema, but the parameter passed is the lower version of jsonschema, so I need to update the parameter version used by 'schema', For example, upgrade to JSONSchema7.
```typescript
// old
// export declare function compile(schema: JSONSchema4, name: string, options?: Partial<Options>): Promise<string>
// fixed
export declare function compile(schema: JSONSchema7, name: string, options?: Partial<Options>): Promise<string>
```

After modification, as follows
```typescript
const res = await json2ts.compile(
        {
            extends: {
                title: 'IResponse',
                type: 'any'
            },
            type: 'object',
            additionalProperties: false,
            properties: {
                Result: {
                    type: 'string'
                }
            }
        },
        'ITest'
    )
```

Later, I will submit a PR to fix this problem. hope it can be passed.

**Comment by bcherny** [comment]
Hey thanks for the report, but I'm having trouble understanding what exactly you're trying to say. There's a lot of typos.

Could you please post:

1. A sample JSON Schema, in JSON format
2. The actual output
3. The output you would have expected

Thanks!
