### ISSUE TITLE
strictIndexSignatures appears to be broken since at least v11.0.0

### ISSUE THREAD

**Issue by benjamincburns** [bcherny/json-schema-to-typescript#477]
Per the title, it seems the `strictIndexSignatures` option has no effect since v11.0.0.

The below script fetches the latest JSONSchema for NPM's `package.json` file and attempts to generate types for it. In spite of the `strictIndexSignatures: true` at line 20, I still get errors like the following:

```
lib/types.ts:15788:3 - error TS2411: Property 'require' of type 'PackageExportsEntry | PackageExportsFallback | undefined' is not assignable to 'string' index type 'PackageExportsEntry | PackageExportsFallback'.

15788   require?: PackageExportsEntry | PackageExportsFallback;
```

The script in question (depends on `got` to fetch the schema) is here:

```typescript
import { resolve as pathResolve, join as pathJoin } from "path";
import { writeFileSync } from "fs";

import got from "got";
import { compile } from "json-schema-to-typescript";
import type { JSONSchema4 } from "json-schema";

const url =
  "https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/package.json";
const outputPath = pathJoin(pathResolve(__dirname, "..", "lib"), "package-json-types.ts");

(async function () {
  try {
    console.log(`Fetching updated JSONSchema for package.json from ${url}`);
    const schema = (await got(url).json()) as JSONSchema4;

    console.log("Converting JSONSchema to TypeScript interfaces");
    const result = await compile(schema, "PackageJson", {
      unreachableDefinitions: true,
      strictIndexSignatures: true,
    });

    console.log(`Writing interfaces to ${outputPath}`);
    writeFileSync(outputPath, result, { encoding: "utf8" });
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
})();
```

**Comment by bcherny** [comment]
This is a dup of https://github.com/bcherny/json-schema-to-typescript/issues/299. Suggestions welcome!

**Comment by benjamincburns** [comment]
@bcherny are you sure it's strictly a duplicate of that issue? I don't see why #299 would prevent the `strictIndexSignatures` flag from simply tacking a `| undefined` onto the end of an index signature.

**Comment by benjamincburns** [comment]
To be clear, in #299 there's a broader issue where there's a conflict between the types of the defined properties and the `additionalProperties` type. In this case I literally just want `strictIndexSignatures` to do exactly what the docs say that it does and "[a]ppend all index signatures with `| undefined`"
