### ISSUE TITLE
Tool generates a non-completely correct file for package-json

### ISSUE THREAD

**Issue by FStefanni** [bcherny/json-schema-to-typescript#479]
Hi,

I have used this tool to generate a `package.json` type description, starting from the [official JSON schema](https://json.schemastore.org/package).

The generated output file is almost correct, but it requires few manual fixes.
So here I report the issues I have found, to allow to improve the tool.

### 1 Linter

Yes, this is not a bug, but since [tslint is deprecated](https://www.npmjs.com/package/tslint) since a lot of time, it could be nice to replace:
```
/* tslint:disable */
```

with:
```
/* eslint-disable */
```

### 2 Error in compiling

There are some places where something as this is generated:

```typescript
{
        "."?: PackageExportsEntry | PackageExportsFallback;
        [k: string]: PackageExportsEntry | PackageExportsFallback;
}
```

And it fails to compile:

```text
Property '"."' of type 'PackageExportsEntry | PackageExportsFallback | undefined' 
is not assignable to 'string' index type 'PackageExportsEntry | PackageExportsFallback'.

15443         "."?: PackageExportsEntry | PackageExportsFallback;
```

The error is that the field `"."` is optional (it is declared with `?:`, but also an "or" with undefined would result in the same error), 
and its type is the same of the "index type" (`[k: string]: PackageExportsEntry | PackageExportsFallback;`), except that the index type is not optional. 
So the fix is to make also the index type optional:

```typescript
{
        "."?: PackageExportsEntry | PackageExportsFallback;
        [k: string]: PackageExportsEntry | PackageExportsFallback | undefined;
}
```

Regards

**Comment by bcherny** [comment]
#1 is fixed in #474.
#2 is tracked in https://github.com/bcherny/json-schema-to-typescript/issues/299 (suggestions welcome!)
