### ISSUE TITLE
Fail to resolve remote reference

### ISSUE THREAD

**Issue by zengfenfei** [bcherny/json-schema-to-typescript#49]
When I try to generate typings from swagger schema(https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v2.0/schema.json), following error reported:

```
ReferenceError: Unable to find referenced file "/some/file/path/http:/json-schema.org/draft-04/schema#/properties/title"                                                                                                                      
    at /Users/xxx/Projects/swagger-typings/node_modules/json-schema-to-typescript/dist/index.js:115:99                  
    at tryFn (/Users/xxx/Projects/swagger-typings/node_modules/json-schema-to-typescript/dist/index.js:288:16)
...
```

**Comment by bcherny** [comment]
You're missing a forward slash in "http:". If you add it, you'll see a more specific error message that remote refs are not yet supported. PRs are welcome :)

**Comment by zengfenfei** [comment]
Well, thanks. I'll try to create a PR for this.

**Comment by bcherny** [comment]
Tracking in https://github.com/bcherny/json-schema-to-typescript/issues/3
