### ISSUE TITLE
allOf is generated as an union type

### ISSUE THREAD

**Issue by ericmorand** [bcherny/json-schema-to-typescript#491]
We are facing a very strange behavior with `allOf`: the generated type is a _type alias_ instead of a proper type.

Take this code sample:

```ts
import {compile, JSONSchema} from "json-schema-to-typescript";

const schema: JSONSchema = {
    allOf: [
        {
            type: "object",
            properties: {
                foo: {
                    type: "string"
                }
            }
        },
        {
            type: "object",
            properties: {
                bar: {
                    type: "string"
                }
            }
        }
    ]
};

compile(schema, 'Schema').then((output) => {
    console.log(output);
})
```

The content of `output` is:

```ts
export type Schema = {
        foo?: string;
        [k: string]: unknown;
    } & {
        bar?: string;
        [k: string]: unknown;
    }
```

Instead of the expected:

```ts
export type Schema = {
        foo?: string;
        bar?: string;
        [k: string]: unknown;
    }
```

It creates a very big quality issue: every schema referenced by a `allOf` directive is exported as a discrete type, making them publicly available and thus contractual. They are internal schemas, just known at schema-writing time and they should not be emitted as some public types.

Is this a known issue?

**Comment by GabenGar** [comment]
You are misunderstanding `allOf` keyword. It's not an equivalent to `extends` where you can slap random fields on existing value. For a `allOf` value to be valid, the _input must conform to all schemas listed in the array separately_. Thus a type alias is the only way to represent this, since schemas can validate for primitive values, not only objects.

**Comment by bcherny** [comment]
If you want the following output:

```
export type Schema = {
    foo?: string;
    bar?: string;
    [k: string]: unknown;
}
```

You should use the following JSON Schema:

```json
{
    "type": "object",
    "properties": {
        "foo": {
            "type": "string"
        },
        "bar": {
            "type": "string"
        }
    }
}
```

If you're not comfortable with JSON Schema syntax, consider starting here: https://json-schema.org/learn/getting-started-step-by-step.html
