### ISSUE TITLE
Example for multiple Types needed

### ISSUE THREAD

**Issue by coolusaHD** [bcherny/json-schema-to-typescript#494]
Hello,

can you provide an example where I can generate multiple types with only one JSON file.

I browsed a bit to your code but couldn't find anything.

Thanks in advance.

**Comment by bcherny** [comment]
Can you comment with your JSON file, and the output you’d expect?

**Comment by coolusaHD** [comment]
Thanks for the quick answer.

I would like as result something like:
`export interface a {
    name: string;
}

export interface b {
    age: number;
}
`
But I don't know how I can structure the json to get this output.

**Comment by coolusaHD** [comment]
my currently workaround is 
```
{
  "title": "All",
  "description": "xyz",
  "oneOf": [
    {
      "$ref": "#/definitions/test1"
    },
    {
      "$ref": "#/definitions/test2"
    }
  ],
  "definitions": {
    "test1": {
      "type": "object",
      "description": "aaaa",
      "properties": {
        "a": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "test5"
      ]
    },
    "test2": {
      "properties": {
        "b": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}
```
which generates to:
´´´
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * xyz
 */
export type All = Test1 | Test2;

/**
 * aaaa
 */
export interface Test1 {
  a?: string;
}
export interface Test2 {
  b?: string;
}
```

But if I remove the oneOf it generates 
```
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * xyz
 */
export interface All {
  [k: string]: unknown;
}

```

**Comment by bcherny** [comment]
You want to enable the `unreachableDefinitions` option, then remove the `allOf`:

```json
{
  "title": "All",
  "description": "xyz",
  "definitions": {
    "test1": {
      "type": "object",
      "description": "aaaa",
      "properties": {
        "a": {
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "test5"
      ]
    },
    "test2": {
      "properties": {
        "b": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }
}
```
