### ISSUE TITLE
Add support for "extends" keyword

### ISSUE THREAD

**Issue by bcherny** [bcherny/json-schema-to-typescript#5]

**Comment by alesandroLang** [comment]
Hi Boris,

Do you accept PR's on that topic?

**Comment by bcherny** [comment]
@alesandroLang PRs are always welcome. See [contributing.md](https://github.com/bcherny/json-schema-to-typescript/blob/master/CONTRIBUTING.md) for helpful tips.

**Comment by alesandroLang** [comment]
there it is #111

**Comment by bcherny** [comment]
Fixed in ec62911
