### ISSUE TITLE
Correctly assigning type array enum 

### ISSUE THREAD

**Issue by r4881t** [bcherny/json-schema-to-typescript#500]
Hi,

My Schema looks like below

```json
...
"availableOnPlatform": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "ios",
          "web",
          "android"
        ]
      },
      "minItems": 1,
      "description": "A string signifying if the dApp is available on which platform - web, iOS, android"
    },
...
```

After converting it into interface I get following

```typescript

/**
   * A string signifying if the dApp is available on which platform - web, iOS, android
   *
   * @minItems 1
   */
  availableOnPlatform: ["ios" | "web" | "android", ...("ios" | "web" | "android")[]];

```

My JSON is as below

```json

 "availableOnPlatform": ["web", "ios"],

```

I keep getting the error

```
Types of property 'availableOnPlatform' are incompatible.
          Type 'string[]' is not assignable to type '["web" | "ios" | "android", ...("web" | "ios" | "android")[]]'.
            Source provides no match for required element at position 0 in target.ts(2322)

```

How can this be resolved? Or what am I doing wrong? I tried with https://www.jsonschemavalidator.net/ and it shows no error with my JSON against the schema

**Comment by geoguide** [comment]
Hm, what am I doing to not get this error. It's possible I don't understand your usecase.

[Here's a link of what I assumed would happen and it is working](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBVDtMQ6BiYhjSdwAeU49DqyXgZEQoAAvKAANoAIgagn5oAAPqB+VJpCLxfyXGwKNx+fwAqqABSC+DCsUSqUyiXy+CK-kASl5AF1zcEEJxBEckJAAGoMaDsSD5Kk0xj0yBMlmoNkc7l8gDkQpD-BDUpDVsUNsE8HcAWg8GYaoTyGdrsgJuCxRwzQ8ZC8iHZzmB7BoXzcZmY7AYzEg-Fg0HUiTp8D0Ii8-IAoqsGIgFvoReyJeAHKgQ8IAHKQCT8oIqBlfMjvQRNrSQI6oRwKVzSPCgJylnTDLD6FAIRDQ4SXasSdnREQGDjYhZMVgcHhBEpAA).
