### ISSUE TITLE
@apidevtools/json-schema-ref-parser @10 requires node > 17

### ISSUE THREAD

**Issue by Floha258** [bcherny/json-schema-to-typescript#511]
It would be good to make a note of it, as this was only introduced in 11.0.4, which might break systems (as it just did for me)

**Comment by giovanniandreuzza** [comment]
They fixed this problem with the new version 10.1.0

https://github.com/APIDevTools/json-schema-ref-parser/compare/v10.0.1...v10.1.0#diff-32f595542782a77486b51f5f938f03e3a9d4552e4a8dff5725732492dee57873

**Comment by giovanniandreuzza** [comment]
I've created this PR: https://github.com/bcherny/json-schema-to-typescript/pull/512

**Comment by bcherny** [comment]
I fixed this by forking JSRP at 10.0.x (we've had to do this a few times, unfortunately), and manually downgrading the `engine` to 16. 

Give json-schema-to-typescript@11.0.5 a shot, and let me know if that fixes the issue. If so, I'll deprecate 11.0.4 on NPM. Thanks!
