### ISSUE TITLE
Types generated with full qualified schema.id url

### ISSUE THREAD

**Issue by rcavalcanti** [bcherny/json-schema-to-typescript#52]
Currently the `schema.id` is favored over the `schema.title` when generating the type name. 

For instance,
```
{
  "id": "http://dummy.com/api/person",
  "title": "Person",
  "type": "object",
  "properties": {
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    }
  }
}
```
will generate 
```
export interface HttpDummyComApiPerson {
  firstName?: string;
  lastName?: string;
  [k: string]: any;
}
```

Although it helps to avoid naming collisions, it's very awkward to have types named after URLs.

I would like to suggest one of the two possible improvements:

- swap the `id` and `title` on index.ts:47
```
this.id = schema.title || schema.id || this.filePath.name || 'Interface1'
```
Which will favor the `title` over the `id`. The down side being that it may cause naming collisions.

- favor the `id`, but generate a namespace

for id = "http://dummy.com/api/person"
we could have
```
namescape DummyComApi { // http protocol dropped
  export interface Person {
    firstName?: string;
    lastName?: string;
    [k: string]: any;
  }
}
```

**Comment by rcavalcanti** [comment]
Another possible solution is to have it passed in the Settings. 

Btw, settings are not available on compileFromFile method, only on compile.

**Comment by bcherny** [comment]
> swap the id and title on index.ts:47

I like this idea - feel free to put up a PR.

> Btw, settings are not available on compileFromFile method, only on compile.

FYI, I am working on a complete rewrite of the compiler to make it easier to work with. Again, feel free to PR if you need this now, and I will merge it.
