### ISSUE TITLE
Feature Request: Generate Classes instead of interfaces

### ISSUE THREAD

**Issue by mattbishop** [bcherny/json-schema-to-typescript#544]
Typescript interfaces are really nice, but some use cases require a Class instead of an interface, especially working with libraries that need classes for data handling. Simple class generation shouldn't be that hard, right?

Also, class generation opens up the possibility of more advanced features like field validation in the setters.

**Comment by bcherny** [comment]
Feel free to write your own generator to do this. You'd want to fork the [`compile`](https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L126) function in your code, replacing [this call](https://github.com/bcherny/json-schema-to-typescript/blob/master/src/index.ts#L176) to `generate()` with your own `generate` function.

**Comment by galah92** [comment]
@mattbishop what did you end up doing?
@bcherny will you accept a PR adding optional parameter to support generation of types instead of interfaces?
