### ISSUE TITLE
`RangeError` for circular references to `oneOf` containing definition with the `$ref`

### ISSUE THREAD

**Issue by christianklotz** [bcherny/json-schema-to-typescript#547]
I have been trying to generate Typescript types from the [Amazon State Language JSON Schema](https://github.com/aws/amazon-states-language-service/blob/master/src/json-schema/bundled.json) which leads to the following error:

```log
RangeError: Maximum call stack size exceeded
```

As far as I can tell this is a circular reference where the [referenced definition itself is a `oneOf`](https://github.com/aws/amazon-states-language-service/blob/52e8c0adb847c6860fa98efb7a371bff552656fa/src/json-schema/bundled.json#L816) which in turn contains the definition with the [`$ref`](https://github.com/aws/amazon-states-language-service/blob/52e8c0adb847c6860fa98efb7a371bff552656fa/src/json-schema/bundled.json#L1136-L1138). 

```json
  "Not": {
    "$ref": "#/properties/States/additionalProperties/oneOf/4/allOf/2/properties/Choices/items/oneOf/18/properties/Not"
  },
```

Removing all unnecessary layers and definitions leaves the following schema.

**Reduced schema**

```json
{
  "type": "object",
  "properties": {
    "States": {
      "type": "object",
      "properties": {
        "Choices": {
          "type": "array",
          "description": "An array of Choice Rules that determines which state the state machine transitions to next.",
          "minItems": 1,
          "items": {
            "type": "object",
            "properties": {
              "Not": {
                "oneOf": [
                  {
                    "type": "object",
                    "properties": {
                      "Not": {
                        "$ref": "#/properties/States/properties/Choices/items/properties/Not"
                      }
                    },
                    "required": [
                      "Not"
                    ]
                  }
                ]
              }
            },
            "required": [
              "Not"
            ]
          },
          "additionalItems": false
        }
      },
      "required": [
        "Choices"
      ]
    }
  },
  "required": [
    "States"
  ]
}
```

**Reduced schema without `oneOf` in referenced type**

The moment the referenced definition is an object, no longer a `oneOf`, the circular reference gets resolved correctly.

```json
{
  "type": "object",
  "properties": {
    "States": {
      "type": "object",
      "properties": {
        "Choices": {
          "type": "array",
          "description": "An array of Choice Rules that determines which state the state machine transitions to next.",
          "minItems": 1,
          "items": {
            "type": "object",
            "properties": {
              "Not": {
                "type": "object",
                "properties": {
                  "Not": {
                    "$ref": "#/properties/States/properties/Choices/items/properties/Not"
                  }
                },
                "required": [
                  "Not"
                ]
              }
            },
            "required": [
              "Not"
            ]
          },
          "additionalItems": false
        }
      },
      "required": [
        "Choices"
      ]
    }
  },
  "required": [
    "States"
  ]
}
```

I'd be happy to take a look myself but would appreciate a few suggestions on where to look, possible routes.

**Comment by christianklotz** [comment]
I looked at the issues earlier but somehow missed #523 which looks very similar.

**Comment by bcherny** [comment]
Dup of #523

**Comment by alexmojaki** [comment]
I disagree with closing this as a duplicate:

1. Per my comment on #523, it seems like that issue isn't an issue at all as the reported schema is invalid.
2. The error is different: `TypeError: Converting circular structure to JSON` vs `RangeError: Maximum call stack size exceeded`.
3. Closing this issue means that future readers are likely to only read the other issue and not this one and most likely get an incomplete picture.

Having said that, the minimal schema given here is confusing to think about. Unlike the other issue, this one passes validation, but it still seems invalid because I can't see how to construct a finite valid object according to the schema:

![Screenshot from 2023-08-27 13-40-15](https://github.com/bcherny/json-schema-to-typescript/assets/3627481/710cb0ee-3c80-4344-80d7-4bfaddf6d47d)
