### ISSUE TITLE
A bit unclear about the purpose of `declareExternallyReferenced` and intention

### ISSUE THREAD

**Issue by v-ahuja** [bcherny/json-schema-to-typescript#550]
My use case is the following:

1. I'd like `schema_one.json` to depend on `schema_two.json`
2. Generated file `schema_two.ts` should reference generated filed `schema_two.ts`

While testing `declareExternallyReferenced false` via the CLI, I see that nothing in definitions is generated in `schema_one.ts`. However, my expectation was that **only external types** wouldn't be generated.

For now, im going to stick everything in one `.json` schema file. I think it might be worthwhile having a bit of a further explanation in the `README.md` as I see other people also asking questions about this.

P.S. Very useful tool and thank you for making it.

**Comment by GabenGar** [comment]
Can you provide the example schemas at least?

**Comment by bcherny** [comment]
Dup of #525
