### ISSUE TITLE
List on json-schema.org

### ISSUE THREAD

**Issue by benjagm** [bcherny/json-schema-to-typescript#554]
Hello! My name is Benjamin from the JSON Schema Community. I came across this cool JSON Schema implementation, and I wanted to congratulate for the great work! KUDOS!

I noticed that it's not listed on our [implementations page](https://json-schema.org/implementations.html), but we'd love it to be.
If you'd like to add this implementation to that page, please feel free to [create a pull request](https://github.com/json-schema-org/website) to this [file](https://github.com/json-schema-org/website/blob/main/pages/implementations/main.md)!

I'd like to use this opportunity to invite you to join the [JSON Schema Community in Slack](https://json-schema.org/slack), where we have some interesting channels like #implementers where you could connect with other relevant maintainers in the ecosystem.

Thanks for enhancing the JSON Schema ecosystem!

**Comment by bcherny** [comment]
Sure! Here you go: https://github.com/json-schema-org/website/pull/272
