### ISSUE TITLE
Add option to remove `[k: string]: unknown | undefined;` from generated types

### ISSUE THREAD

**Issue by jahirfiquitiva** [bcherny/json-schema-to-typescript#572]
Hi

I would like to make the generated types a bit more strict by removing the types:
`[k: string]: unknown | undefined;`

Is that possible? Otherwise, would you mind implementing such feature?
Thanks in advance!

**Comment by sudhanshug16** [comment]
I think you can use `additionalProperties: false,` to achieve this

**Comment by jahirfiquitiva** [comment]
I have it like that and it still generates them @sudhanshug16

**Comment by sudhanshug16** [comment]
Maybe you have `additionalProperties: true` in your JSON schema.

If that's the case and you really don't want to have that generic signature in your types, you can set additionalProperties to false on all the nodes, I am using this:

```ts

export function setNoAdditionalProps(schema: SchemaObject) {
  if (schema.type === "object") {
    schema.additionalProperties = false;
    for (const [, value] of Object.entries(schema.properties ?? {})) {
      setNoAdditionalProps(value as SchemaObject);
    }
  }
  if (schema.type === "array") {
    setNoAdditionalProps(schema.items as SchemaObject);
  }
}

```

**Comment by jahirfiquitiva** [comment]
@sudhanshug16 sorry it took me so long to get back to this, but I wanted to let you know your `setNoAdditionalProps` function worked fine 🙌 Thanks for the help!
