### ISSUE TITLE
Add yaml support

### ISSUE THREAD

**Issue by codan84** [bcherny/json-schema-to-typescript#577]
If one writes their schemas in `yaml` file format, is there a simple way to generate types using the CLI tool?
If not - could a support for that be added please?

**Comment by alexanderkrum** [comment]
@bcherny picking this up

**Comment by alexanderkrum** [comment]
https://github.com/bcherny/json-schema-to-typescript/pull/588

**Comment by bcherny** [comment]
Published 14.0.2.
