### ISSUE TITLE
wrongly transformed array of string

### ISSUE THREAD

**Issue by eMerzh** [bcherny/json-schema-to-typescript#584]
hello ...
i found an issue eslint-types/eslint-define-config that i think comes from the transformation of the jsonschema to typescript

this schema: 

https://github.com/eslint/eslint/blob/b91f9dc072f17f5ea79803deb86cf002d031b4cf/lib/rules/camelcase.js#L30

is transformed

to 

```ts
{
  ignoreDestructuring?: boolean
  ignoreImports?: boolean
  ignoreGlobals?: boolean
  properties?: "always" | "never"
  allow?: [] | [string]
}
```

the issue is allow should be `string[]` instead of `[string]`

**Comment by eMerzh** [comment]
as i understand it should be an array of string , not super familiair with json schema, but how is it supposed to be ?

**Comment by Shinigami92** [comment]
> as i understand it should be an array of string , not super familiair with json schema, but how is it supposed to be ? 

I think they want to tell you that the issue is in **eslint**, not in json-schema

**Comment by eMerzh** [comment]
hehe, i got the hint @Shinigami92  :) ... 

but if i look https://json-schema.org/understanding-json-schema/reference/array 

What i understand (again, i'm a noob in jsonschema) 

> In the following example, we define that each item in an array is a number:
```{
  "type": "array",
  "items": {
    "type": "number"
  }
}
```

```js
[1, 2, 3, 4, 5]
```


This let me think that 
```{
  "type": "array",
  "items": {
    "type": "string"
  }
}
```
should allow
```js
["one", "two", "three"]
```

No ? 
if no (which is possible), can you help me find how is it supposed to look ?

**Comment by Shinigami92** [comment]
`items: [{type:'string'}]` != `items: {type:'string'}`

**Comment by eMerzh** [comment]
oook :) thanks... let's go open a Pr there :)
