### ISSUE TITLE
Update to glob 10

### ISSUE THREAD

**Issue by blakethomp** [bcherny/json-schema-to-typescript#587]
The current version of glob in this package has an indirect security vulnerability from [inflight](https://security.snyk.io/package/npm/inflight), glob can be updated to v10, and glob-promise can be removed since newer versions of glob are async.

**Comment by PieterVanEde** [comment]
I also had problems with the version of glob that is currently used, as the version of glob in my project (glob 10) and the version bundled with json-schema-to-typescript conflicted. I'll raise a PR to update the glob version (although the project seems to bork atm on my local machine.
