### ISSUE TITLE
Remove deprecated deps @types/prettier

### ISSUE THREAD

**Issue by pcorpet** [bcherny/json-schema-to-typescript#593]
The package [prettier](https://www.npmjs.com/package/prettier) now includes the types, and the [@types/prettier](https://www.npmjs.com/package/@types/prettier) is deprecated. Can you remove it from your deps please?

If you think it's valid, I can send a PR.

**Comment by evgeny-myasishchev** [comment]
would be good to have it released, it breaks our builds
