### ISSUE TITLE
Indirect dependency on es5-ext: flagged as malicious by some security scanners

### ISSUE THREAD

**Issue by fardjad** [bcherny/json-schema-to-typescript#595]
This package [indirectly](https://npmgraph.js.org/?q=json-schema-to-typescript#select=maintainer%3Amedikoo) depends on [es5-ext](https://github.com/medikoo/es5-ext) (via [`cli-color`](https://github.com/medikoo/cli-color) by the same author). `es5-ext` has a post-install script that does something unrelated to the package. Luckily, it is [**currently** harmless](https://github.com/medikoo/es5-ext/blob/f76b03d8c49ce4871f37f428c0e1d3ee6637fcc4/_postinstall.js). However, it may or may not escalate to something more serious in the future. As such, some security scanners are flagging `json-schema-to-typescript` and its dependents as unsafe.

Here are some examples:

When `json-schema-to-typescript` is installed with [`safe-npm`](https://socket.dev/blog/introducing-safe-npm), it shows a scary prompt:

```
(socket) es5-ext@0.10.64 contains risks:
  Install scripts - Install scripts are run when the package is installed. The majority of malware in npm is hidden in install scripts.
  Protestware/Troll package - This package is a joke, parody, or includes undocumented or hidden behavior unrelated to its primary function.
```

Running [`npx npq install es5-ext --dry-run`](https://github.com/lirantal/npq) shows the following warning message:

```
npx npq install es5-ext --dry-run
⚠ Supply Chain Security
  ✔ Checking for known vulnerabilities
  ✔ Verifying registry signatures for package
  ✖ Verifying package provenance
  ✔ Identifying package author...
✔ Package Health
  ✔ Checking for typosquatting
  ✔ Checking availability of a LICENSE
  ✔ Checking package maturity
⚠ Malware Detection
  ✖ Checking package for pre/post install scripts
  ✔ Identifying package repository...
  ✔ Detecting expired domains for authors account...
  ✔ Checking package download popularity

Detected possible issues with the following packages:
  [es5-ext@latest]
    - Unable to verify provenance: the package was published without any attestations.
    - detected a possible malicious intent script, act carefully: postinstall:  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
```

There are more [reports](https://github.com/medikoo/es5-ext/issues?q=is%3Aissue+sort%3Aupdated-desc+postinstall) in the `es5-ext` repository indicating that `es5-ext` has been flagged by other security scanners.

Leaving aside the politics and the unfortunate circumstances that led to this situation, the (indirect) dependency can cause complications when using `json-schema-to-typescript`. That is especially problematic in cases where users have limited control over security scanners or when whitelisting `es5-ext` isn't an option.

I don't know to what extent the author or contributors of `json-schema-to-typescript` view this as an issue, nor do I have a specific solution in mind but I wanted to highlight this as a potential concern and raise awareness.

**Comment by bcherny** [comment]
Thanks for the heads up, but as you said, there are many packages depending on es5-ext, and the issue should be fixed upstream.

**Comment by fardjad** [comment]
@bcherny Actually, the reason `json-schema-to-typescript` pulls `es5-ext` is because it has a dependency on `cli-color` and it appears to be lightly used [here](https://github.com/bcherny/json-schema-to-typescript/blob/master/src/utils.ts). That is the only place I could find in the code that has a dependency on that package.

By removing that dependency/replacing it with another module such as [this](https://www.npmjs.com/package/ansi-colors), this issue can be fixed.
