### ISSUE TITLE
Possible to perform batch compilation from CLI?

### ISSUE THREAD

**Issue by RickCarlino** [bcherny/json-schema-to-typescript#62]
Hi,

Thanks for the great library, and sorry if this question has already been answered in the docs (I was not able to find anything as far as I know).

Is it possible to perform batch compilation? For example, with the following directory structure:

```
+- json_schema
  +-foo.json
  +-bar.json
```

is it possible to create the following output?

```
+- json_schema
  +-foo.json
  +-foo.d.ts
  +-bar.json
  +-bar.d.ts
```
Thanks again for all the great work on this project. It's very much appreciated.

**Comment by RickCarlino** [comment]
As a side note, I was able to solve the problem using the script below, but am still curious if the CLI supports the functionality natively:

```
"use strict";
var JS2TS = require("json-schema-to-typescript");
var glob = require("glob");
var fs = require("fs");
glob("./*.json", function (err, files) {
  if (err) {
    console.log(err);
    console.log(files);
  }
  else {
    files.map(function (file) {
      JS2TS
        .compileFromFile(file)
        .then(function (data) {
          var newFile = file.split(".")
          newFile.pop();
          fs.writeFileSync("./" + newFile.join("") + ".d.ts", data);
        });
    });
  }
});
```

**Comment by bcherny** [comment]
Hi @RickCarlino! There is no way to do this today, but feel free to PR this feature. Also see https://github.com/bcherny/json-schema-to-typescript/issues/16.

cc @erykpiast
