### ISSUE TITLE
Option to keep primitive types in place

### ISSUE THREAD

**Issue by fudom** [bcherny/json-schema-to-typescript#624]
I don't want to outsource primitive types. For example instead of `export type Name = string` assign `string` directly on the property. No need to separate it as own type.

Btw. I want to use StrictPascalCase. Instead of `ID` or `UUID` use `Id` or `Uuid`. I have a parameter named `id` with title "ID (UUID)" and get a type name of "IDUUID". Which is just a string. And for each object it create a new increment type like "IDUUID1" etc. Even if "string === string".

**Comment by bcherny** [comment]
To do that, remove the `title` from your property. When `title` or `id` are present, JSTT infers that you usually want to name the property.
