### ISSUE TITLE
Cannot find type definition file for 'lodash'.  type error in version 15 and above

### ISSUE THREAD

**Issue by utajum** [bcherny/json-schema-to-typescript#625]
Probably happens because of this commit https://github.com/bcherny/json-schema-to-typescript/commit/a1d22d89708cc1c5a49d6b1325068ccaf1144a5d

The error is the same as this one which was fixed
https://github.com/bcherny/json-schema-to-typescript/pull/362

**Comment by bcherny** [comment]
Fixed in 15.0.2
