### ISSUE TITLE
Allow for deduplication

### ISSUE THREAD

**Issue by Bluscream** [bcherny/json-schema-to-typescript#629]
I have a bunch of schemas for different responses from a API: https://github.com/Bluscream/grayjay-source-pietsmietde/tree/master/schemas/pietsmiet.de
And i would like to be able to convert them to .d.ts files, but the problem is that some of them include duplicates (a type being used by multiple responses and therefor in multiple

**Comment by bcherny** [comment]
Dup of https://github.com/bcherny/json-schema-to-typescript/issues/258
