### ISSUE TITLE
Allow configuration of $refOptions in CLI application

### ISSUE THREAD

**Issue by ndopj** [bcherny/json-schema-to-typescript#631]
Issue solved here: https://github.com/APIDevTools/json-schema-ref-parser/issues/199 introduced new argument in **json-schema-ref-parser**.
```javascript
$refOptions: {
        dereference: {
            externalReferenceResolution: "root"
        }
    }
```
This argument guarantees that during resolving deeper references (N-2+, references within references) the base URI will remain unchanged (which does not happen in default behaviour).

Currently it is not possible to pass `$refOptions` in **json-schema-to-typescript** CLI application, but it is already possible to configure it for `compile()` and `compileFromFile()` API methods. Due to this reason its not possible to use CLI application with schema layout as outlined in the linked issue to generate correct Typescript output.

I would like to ask for implementation of this option. Would do it myself, but I am not very experienced within JS/TS and with `minimist` library used to parse command line arguments. If full `$refOptions` are too much of an overhead to be added, I would be glad for at least option for `externalReferenceResolution` to be added separately and passed manually to the `$refOptions`.

Thanks in advance !

**Comment by bcherny** [comment]
This is supported. You'll want to be careful to escape the `$` in `$refOptions` when passing it into the CLI, so bash doesn't interpret it first:

```sh
json2ts your-schema.json --\$refOptions.dereference.externalReferenceResolution=root
```
