### ISSUE TITLE
Shouldn't type for object with `additionalProperties` be `Partial<{[k: string]: ElementType}>` rather than `{[k: string]: ElementType}`?

### ISSUE THREAD

**Issue by seiyab** [bcherny/json-schema-to-typescript#636]
For object with type `{[k: string]: ElementType}`, TSC considers any key access will yield `ElementType`.
However, for practical object with `additionalProperties`, it doesn't have entries for some (technically say, most) keys. Sometimes it will yield `undefined`.
Isn't it safer to get such type `Partial<{[k: string]: ElementType}>`?

**Comment by bcherny** [comment]
I'm not totally sure what you mean. Could you share a complete example of a JSON Schema, and the output you expect?

**Comment by seiyab** [comment]
I'm sorry for unclear description. I didn't have enough time to show complete & easy to understand example and I'm not an English speaker.
I'll add concrete minimal example later.

**Comment by seiyab** [comment]
@bcherny I updated description. Ask me if it's still unclear.

**Comment by seiyab** [comment]
Ah, `strictIndexSignatures` is almost I wanted. Maybe no need to add any feature.
Can I use this through CLI? Both didn't work:
- `npx json2ts -i ./my-type.json -o ./my-type.ts --strinct-index-signatures`
- `npx json2ts -i ./my-type.json -o ./my-type.ts --strinctIndexSignatures`
