### ISSUE TITLE
cwd option doesn't seem to be working

### ISSUE THREAD

**Issue by itslenny** [bcherny/json-schema-to-typescript#81]
When I use the following code
```
let json2tsPromise = json2ts.compile(jsonObject, fileName, {
    cwd: '/some/absolute/path/here',
    declareReferenced: true
});
```

I get an error that the path for the reference cannot be found and it uses the `process.cwd()` path as the base path instead of what I pass into cwd. I stepped through the code a bit and it seems like it's not being passed into the `dereference()` function. I couldn't track down exactly where that parameter is getting lost.

As a work around I can just do `process.chdir('/some/absolute/path/here')` and then run `compile()` without a cwd option and it works fine.

**Comment by bcherny** [comment]
Thanks for the report @itslenny! Fix is published in 4.2.0.
