### ISSUE TITLE
Add support for inverse transformation (TS => JSON-Schema)

### ISSUE THREAD

**Issue by rogerpadilla** [bcherny/json-schema-to-typescript#82]
Thanks for sharing this cool project!

Have you considered adding support for the inverse transformation (TS => JSON-Schema)?

**Comment by bcherny** [comment]
Hi @rogerpadilla! There is https://github.com/YousefED/typescript-json-schema, though I guess it should be possible to take advantage of the common AST provided in this package to do the reverse transformation. We would need a TS -> AST parser, and AST -> JsonSchema generator.

PRs are welcome if you'd like to give this a shot!

**Comment by bcherny** [comment]
Closing this, and directing anyone that has this use case to https://github.com/YousefED/typescript-json-schema.
