### ISSUE TITLE
Why [k:string]: any

### ISSUE THREAD

**Issue by snytkine** [bcherny/json-schema-to-typescript#83]
I just ran the example from the npm documentation page, using same schema object as in documentation but got different result.

This is the result that should be generated according to documentation page on npm 

```
export interface ExampleSchema {
  firstName: string;
  lastName: string;
  /**
   * Age in years
   */
  age?: number;
  hairColor?: ("black" | "brown" | "blue");
}
```

This is what I am getting ( notice [k:strubg]:any )

```
export interface ExampleSchema {
  firstName: string;
  lastName: string;
  /**
   * Age in years
   */
  age?: number;
  hairColor?: ("black" | "brown" | "blue");
  [k: string]: any;
}

```
I noticed I can get rid of that extra stuff by adding 
"additionalProperties": false to my schema
but that was not part of the sample schema.
I think you should update the README file.

**Comment by bcherny** [comment]
Thanks for the report @snytkine!
