### ISSUE TITLE
json2ts --help fails with error

### ISSUE THREAD

**Issue by ikokostya** [bcherny/json-schema-to-typescript#85]
**Versions** 
* `json-schema-to-typescript@4.2.1`
* `node v6.10.2`

**Code**

```
$ ./node_modules/.bin/json2ts --help
```

**Actual behavior**
```
(node:129599) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Cannot find module '../package.json'
```

**Expected behavior**
No errors.

I think this happen, because `bin` field in `package.json` [refers](https://github.com/bcherny/json-schema-to-typescript/blob/master/package.json#L7) to `dist/src/cli.js`, but `cli.js` [requires](https://github.com/bcherny/json-schema-to-typescript/blob/90fc4d80175e7ee4dd91cafd6093585eb4f5e19e/src/cli.ts#L59) `package.json` by  `../package.json` path.

**Comment by bcherny** [comment]
Again, thanks for the report! Fix is also published in 4.3.0.
