### ISSUE TITLE
json2ts fails while read from STDIN

### ISSUE THREAD

**Issue by ikokostya** [bcherny/json-schema-to-typescript#86]
**Version**
* `nodejs v6.10.2`
* `json-schema-to-typescript@4.2.1`

**Code**

```
$ cat test.json 
{}
$ cat test.json | node_modules/.bin/json2ts 
Path must be a string. Received undefined
$ echo $?
1
```

**Expected behavior**
No errors. 

Looks like this is problem with strict argument checking in `path` module which was introduced in nodejs 6: https://github.com/nodejs/node/pull/5348

**Comment by bcherny** [comment]
Thanks for the report @ikokostya! Fix is published in 4.3.0.
