### ISSUE TITLE
json2ts returns empty ts interface for an array json schema

### ISSUE THREAD

**Issue by ducin** [bcherny/json-schema-to-typescript#92]
Following schema is valid, but running it against `json2ts` returns empty result:

```
{
  "id": "Countries",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "string",
        "minLength": 2,
        "maxLength": 2,
        "pattern": "[A-Z]+"
      },
      "name": {
        "type": "string"
      }
    },
    "required": ["id", "name"]
  }
}
```

to be precise, it returns only the header comment:

```
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/
```

but the typescript interface itself is missing.

**Comment by bcherny** [comment]
Thanks for the report @ducin! Fix is published in 4.4.0.

**Comment by ducin** [comment]
many thanks for a quick response and successful solution! Works fine now, generates this now:
```
export type Countries = {
      id: string;
      name: string;
      [k: string]: any;
    }[];
```

**Comment by bcherny** [comment]
No problem! Will address indentation separately BTW - I wanted to get a solution out first.

**Comment by ducin** [comment]
indentation is far from must-have ;) thanks again!
PS strange that the repo has 349 stars and nobody fell with this problem before ;)

**Comment by bcherny** [comment]
The issue was that for anything other than interfaces, IDs were not honored as markers that a type should be declared. Anecdotally, none of my personal use cases have arrays with IDs, and some have titles, which work as expected :)
