### ISSUE TITLE
New option to set additionalProperties to false by default

### ISSUE THREAD

**Issue by battmanz** [bcherny/json-schema-to-typescript#93]
According to the spec additionalProperties is true by default, but it would be nice if this library had an option to set the default to false. That way you could avoid having `[k: string]: any` show up all over the place.

**Comment by bcherny** [comment]
So this would be the first explicit departure from the spec, and so far I have been careful to stick closely to the spec. There would need to be significant interest in this feature to think about adding it.

A few possible implementations come to mind (ordered from worst to best, easiest to hardest):

1. Hardcode the option
2. Add the ability to add custom normalizer steps
3. Pull out normalization logic into its own module, let users configure that

In the meantime, you can try preprocess the schema yourself to add `additionalProperties=false` everywhere.

**Comment by battmanz** [comment]
I don't know which implementation is the right choice, but I would like to give some motivation for this feature. My company has an API that allows searching for people. I can send a JSON object with my search criteria to the API and it will return all people that match. For example:

```ts
const mySearchCriteria = {
  first: 'Elvi*',
  last: 'Pres*',
  minAge: 5,
  maxAge: 22
};
```

The (simplified) schema looks something like:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Person Search Criteria",
  "properties": {
    "first": {
      "type": "string"
    },
    "last": {
      "type": "string"
    },
    "minAge": {
      "type": "number"
    },
    "maxAge": {
      "type": "number"
    }
  }
}
```

My personal preference would be to add `"additionalProperties": false` to the schema, but there is a committee that makes those decisions. I have raised my voice, but it was ultimately decided that we want to allow additional properties to "future proof" the API. So it is what it is.

After running my schema through JSTT, I get the following interface:

```ts
export interface PersonSearchCriteria {
  first?: string;
  last?: string;
  minAge?: number;
  maxAge?: number;
  [k: string]: any;
}
```

Because of the index signature, the interface is almost useless at catching compile-time errors. For example, I get no errors with the following code:

```ts
let p: PersonSearchCriteria;
p = { fist: 'Oops! Misspelled first', list: 'Also misspelled last' };
p = { foo: 'What the heck is foo?' };
```
If I remove the index signature, then I get errors in both cases. Hence, my motivation to have the option to set `additionalProperties` to false. I need this, so I'm going to write a script that will remove the index signatures after the interface has been generated.

Because I need this, I'm guessing that others do to. It would make a great addition to this library. I realize this is a departure from the spec, but only if the option is explicitly turned on. By default, this library will still be spec compliant.

**Comment by bcherny** [comment]
> Because of the index signature, the interface is almost useless at catching compile-time errors.

@battmanz Isn't that the "future proofing" at work? :)

Joking aside, you may want to bring this up with your committee. Consumers of your JSON-Schema will have the same issue with lack of safety, won't they? This is usually solved with some sort of versioning.

**Comment by battmanz** [comment]
@bcherny Ha ha! Agreed!

**Comment by StAn187** [comment]
Sorry to comment on the dead issue but I had the same requirement.

Here's a patch how it could be implemented. It adds a cli/compiler option `additionalProperties=[true|false]`:

    Index: src/cli.ts
    IDEA additional info:
    Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
    <+>UTF-8
    ===================================================================
    --- src/cli.ts	(date 1533289809000)
    +++ src/cli.ts	(date 1533289853000)
    @@ -12,6 +12,10 @@
         help: ['h'],
         input: ['i'],
         output: ['o']
    +  },
    +  boolean: ['additionalProperties'],
    +  default: {
    +    additionalProperties: true
       }
     }))
     
    @@ -72,14 +76,21 @@
     
       --cwd=XXX
           Root directory for resolving $ref
    +
       --declareExternallyReferenced
           Declare external schemas referenced via '$ref'?
    +
       --enableConstEnums
           Prepend enums with 'const'?
    +
       --style.XXX=YYY
           Prettier configuration
    +
       --unreachableDefinitions
           Generates code for definitions that aren't referenced by the schema
    +
    +  --additionalProperties=[true|false]
    +      Set the default value for additional properties (default: true)
     `
       )
     }
    Index: src/index.ts
    IDEA additional info:
    Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
    <+>UTF-8
    ===================================================================
    --- src/index.ts	(date 1533289809000)
    +++ src/index.ts	(date 1533289853000)
    @@ -15,6 +15,7 @@
     export { EnumJSONSchema, JSONSchema, NamedEnumJSONSchema } from './types/JSONSchema'
     
     export interface Options {
    +  additionalProperties: boolean
       bannerComment: string
       cwd: string
       declareExternallyReferenced: boolean
    @@ -24,6 +25,7 @@
     }
     
     export const DEFAULT_OPTIONS: Options = {
    +  additionalProperties: false,
       bannerComment: `/**
     * This file was automatically generated by json-schema-to-typescript.
     * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
    @@ -84,7 +86,7 @@
     
       return format(generate(
         optimize(
    -      parse(await dereference(normalize(schema, name), _options.cwd), _options)
    +      parse(await dereference(normalize(schema, options, name), _options.cwd), _options)
         ),
         _options
       ), _options)
    Index: src/normalizer.ts
    IDEA additional info:
    Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
    <+>UTF-8
    ===================================================================
    --- src/normalizer.ts	(date 1533289809000)
    +++ src/normalizer.ts	(date 1533289853000)
    @@ -1,10 +1,11 @@
     import { whiteBright } from 'cli-color'
    +import stringify = require('json-stringify-safe')
     import { cloneDeep } from 'lodash'
    +import { Options } from './index'
     import { JSONSchema, NormalizedJSONSchema } from './types/JSONSchema'
     import { justName, log, mapDeep, toSafeString } from './utils'
    -import stringify = require('json-stringify-safe')
     
    -type Rule = (schema: JSONSchema, rootSchema: JSONSchema, fileName?: string) => JSONSchema
    +type Rule = (schema: JSONSchema, rootSchema: JSONSchema, options: Partial<Options>, filename?: string) => JSONSchema
     const rules = new Map<string, Rule>()
     
     rules.set('Destructure unary types', schema => {
    @@ -29,24 +30,24 @@
     })
     
     // TODO: default to empty schema (as per spec) instead
    -rules.set('Default additionalProperties to true', (schema, rootSchema) => {
    +rules.set('Default additionalProperties', (schema, rootSchema, options) => {
       if (stringify(schema) === stringify(rootSchema) && !('additionalProperties' in schema)) {
    -    schema.additionalProperties = true
    +    schema.additionalProperties = options.additionalProperties
       }
       return schema
     })
     
    -rules.set('Default top level `id`', (schema, rootSchema, fileName) => {
    +rules.set('Default top level `id`', (schema, rootSchema, _options, fileName) => {
       if (!schema.id && stringify(schema) === stringify(rootSchema)) {
         schema.id = toSafeString(justName(fileName))
       }
       return schema
     })
     
    -export function normalize(schema: JSONSchema, filename?: string): NormalizedJSONSchema {
    +export function normalize(schema: JSONSchema, options: Partial<Options>, filename?: string): NormalizedJSONSchema {
       let _schema = cloneDeep(schema) as NormalizedJSONSchema
       rules.forEach((rule, key) => {
    -    _schema = mapDeep(_schema, schema => rule(schema, _schema, filename)) as NormalizedJSONSchema
    +    _schema = mapDeep(_schema, schema => rule(schema, _schema, options, filename)) as NormalizedJSONSchema
         log(whiteBright.bgYellow('normalizer'), `Applied rule: "${key}"`)
       })
       return _schema

**Comment by LiangMingChen** [comment]
I am running this as well 
Is it possible to fix this with the suggestion from StAn187?
