### ISSUE TITLE
declareReferenced option is ignored

### ISSUE THREAD

**Issue by harrygr** [bcherny/json-schema-to-typescript#97]
Since v4.* if `declaredReferenced` is set to `false` the resultant typescript output still includes schemas referenced by `$ref`.

**Comment by bcherny** [comment]
Hi @harrygr - there is a test covering this behavior [here](https://github.com/bcherny/json-schema-to-typescript/blob/98e1127bc0a6361f10dce73e757191eb668c407d/test/e2e/ref.1.ts).

I'll need a repro case to help diagnose this.

**Comment by harrygr** [comment]
Hmmm, it seems to only happen in my specific project. Have tried to replicate it in another but can't at the moment. Maybe close this and I'll revisit if I manage to get a repro working

**Comment by bcherny** [comment]
Sounds good.
