### ISSUE TITLE
Missing properties when using oneOf, allOf

### ISSUE THREAD

**Issue by tofuseblue** [bcherny/json-schema-to-typescript#98]
A variant of closed #95 

```json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "properties": {
    "localRequired": {
      "type": "string"
    },
    "localOptional": {
      "type": "string"
    }
  },
  "required": [
    "localRequired"
  ]
}
```

Gives output: 

```ts
export interface Test2 {
  localRequired: string;
  localOptional?: string;
  [k: string]: any;
}
```

With oneOf

```json
{
  "$schema": "http://json-schema.org/schema#",
  "definitions": {
    "i_ref_first": {
      "type": "object",
      "properties": {
        "file": {
          "type": "string"
        }
      },
      "required": [
        "file"
      ]
    },
    "i_ref_second": {
      "type": "object",
      "properties": {
        "group": {
          "type": "string"
        }
      },
      "required": [
        "group"
      ]
    }
  },
  "type": "object",
  "oneOf": [
    {
      "$ref": "#/definitions/i_ref_first"
    },
    {
      "$ref": "#/definitions/i_ref_second"
    }
  ],
  "properties": {
    "localRequired": {
      "type": "string"
    },
    "localOptional": {
      "type": "string"
    }
  },
  "required": [
    "localRequired"
  ]
}
```

Output is: 

```ts
export type Test = (IRefFirst | IRefSecond);

export interface IRefFirst {
  file: string;
  [k: string]: any;
}
export interface IRefSecond {
  group: string;
  [k: string]: any;
}
```

In the later case the local properties are ignored. I understand that the translation to interfaces is not 100% strait forward but trying out JSON validators like JSON Schema Lint the validator will take the local properties into account which I where expecting.

**Comment by bcherny** [comment]
Thanks for the report @tofuseblue!

If I'm reading the spec (https://tools.ietf.org/html/draft-wright-json-schema-validation-01#section-4.3) right, this schema says that a valid object should define the keys `(i_ref_first OR i_ref_second) AND localRequired AND MAYBE localOptional`.

For example, these are **valid**:

```coffee
{
  i_ref_first: ...
  localRequired: ...
}
```

```coffee
{
  i_ref_second: ...
  localRequired: ...
}
```

And these are **invalid**:

```coffee
{
  i_ref_first: ...
  i_ref_second: ...
  localRequired: ...
}
```

```coffee
{
  i_ref_first: ...
}
```

```coffee
{
  localRequired: ...
}
```

As usual, it would be great to get a spec author to confirm this - @handrews would you mind chiming in when you have a minute?

If this interpretation is correct, then this bug is already tracked in https://github.com/bcherny/json-schema-to-typescript/issues/96, and I will close this issue in favor of that one.

**Comment by tofuseblue** [comment]
Yes, your are quite right. You interpret the specification in the same way as I and the problem is covered by #96. Sorry for not seeing that before I filed this one. 
Just to make sure though when using references. You wrote below example as valid. 
{
  i_ref_first:...
  localRequired: ... 
}
I would interpret the specification for a reference to use the identifier as key so it would be.
{
 file: ....
  localRequired: ...
} 
This is perhaps what you meant just want to be clear in what I would expect. I.e. the intersection is between the local properties + the properties of the referenced object.

**Comment by bcherny** [comment]
Tracking in #96.
